set termout off
set linesize 2000 trims on  pagesize 0 feedback off;
SPOOL $PREPROCESS/IND/&1/options.txt;
select Entity
||'|'||TradeId
||'|'||ExternalID
||'|'||StructureID
||'|'||StructureIdorLinkId
||'|'||ComponentTypology
||'|'||ContractTypology
||'|'||PackageTypology
||'|'||ContractUsage
||'|'||Desk
||'|'||Book
||'|'||Folder
||'|'||TradingorBanking
||'|'||CounterpartyGroupCode
||'|'||CounterpartyParentCode
||'|'||CounterpartyChildCode
||'|'||CounterpartyName
||'|'||InternalorExternal
||'|'||replace(TradeDate,'/','-')
||'|'||replace(StartDate,'/','-')
||'|'||replace(ExpiryDate,'/','-')
||'|'||replace(DeliveryDate,'/','-')
||'|'||BuyorSell
||'|'||PutorCall
||'|'||CallCurrency
||'|'||CallAmount
||'|'||PutCurrency
||'|'||PutAmount
||'|'||Notional_INR
||'|'||StrikeRate
||'|'||BankorNonBank
||'|'||CCYPair
||'|'||CurrentSpot
||'|'||PremiumCurrency
||'|'||PremiumAmount
||'|'||SettledPremiumamount
||'|'||UnsettledPremiumamount
||'|'||PremiumSettlementDate
||'|'||FutureCashProceedsCurrency
||'|'||FutureCashProceeds
||'|'||FutureCashProceedsINR
||'|'||MarketValueFinanced
||'|'||MTM_excludingpremiumin_INR
||'|'||MTM_withunsettledpremiaIn_INR
||'|'||CVA
||'|'||DVA
||'|'||BCVA
||'|'||NetBCVAadjustedGMTMin_INR
||'|'||PositionCurrency
||'|'||ForwarddeltaCCY1Amount
||'|'||SpotdeltaCCY1Amount
||'|'||PLCurrency
||'|'||ForwarddeltaCCY2Amount
||'|'||SpotdeltaCCY2Amount
||'|'||GammaCCY
||'|'||GammaAmount
||'|'||Vega_INR
||'|'||Theta_INR
||'|'||Rho_INR
||'|'||UnderlyngCcy
||'|'||Phi_INR
||'|'||Vanna_INR
||'|'||Volga_INR
||'|'||ModifiedDuration
||'|'||UnderlyingNotional
||'|'||UnderlyingorPP
||'|'||OriginalTenor
||'|'||ResidualTenor
||'|'||DealStatus
||'|'||InputID
||'|'||M_H_FWD_RATE
||'|'||FLOWTYPE
||'|'||FLOWTYPE1
||'|'||FLOWTYPE2
||'|'||FLOWTYPE3
||'|'||FLOWTYPE4
||'|'||FLOWAMOUNT
||'|'||CCY
||'|'||CASHFLOWDATE
from VW_OPTION_CF where FLOWAMOUNT != 0;
set termout on
