[package]
name = "cf_od"
version = "1.0.4961"
authors = ["Tarun Jaiswal <tarun.j@surya-soft.com>"]

[dependencies]
clap = "2.32.0"
sdb_io = { path = "../../../libraries/sdb_io" }
rbdate = { path = "../../../libraries/RBDate" }
health_report = { path = "../../../libraries/health_report" }
protobuf = { version = "2.22.0", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
