CREATE TABLE Repo_Rev_Repo
(
    dealno Varchar2(64),
    deal_date date,
    value_dt_1st_leg date,
    deal_time Varchar2(64),
    nature Varchar2(64),
    deal_stat Varchar2(64),
    dealtype Varchar2(64),
    slr_typ Varchar2(64),
    security Varchar2(64),
    category Varchar2(64),
    sub_category Varchar2(64),
    desk Varchar2(64),
    portfolio Varchar2(64),
    accounting_section Varchar2(64),
    counterparty Varchar2(64),
    counterparty_full_name Varchar2(256),
    currency Varchar2(64),
    face_val Number(24),
    haircut_margin Number(24),
    book_val Number(24),
    repo_rate Number(24,4),
    ytm Number(24,4),
    valuedt date,
    price Number(24,4),
    hold_rate Number(24,4),
    holding_book_value Number(24,4),
    settle_amt_1st_leg Number(24,4),
    accrued_interest Number(24,4),
    repointerest Number(24,4),
    settle_amt_2nd_leg Number(24,4),
    brokerage Number(24,4),
    broker Varchar2(256),
    dealer_id Varchar2(64),
    dealer_name Varchar2(256),
    authoriser Varchar2(256),
    auth_dt date,
    auth_time Varchar2(64),
    remarks Varchar2(256),
    nds_entry_time Varchar2(128),
    dvpiii Number(24,4),
    entity Varchar2(64),
    bank_non_bank Varchar2(64),
    air_aip Number(24,4)
);

