[package]
name = "protobuf-generator"
version = "0.1.0"
authors = ["sougata bhattacharjee <sougata.b@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protoc-rust = "2.28.0"
protobuf = { version = "2.15.0", features = ["with-bytes"] }
