[package]
name = "account_level_duration"
version = "1.0.0"
authors = ["Shashank <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.33.1"
slog-term = "2.6.0"
slog-async = "2.5.0"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.11"
time = "0.2.16"
sdb_dyn_proto_rdr = { path = "../../libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../surya/libraries/sdb_agg_rules" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sdb_io = { path = "../../libraries/sdb_io" }
