[package]
name = "sdb_cf_gen"
version = "1.1.0"
authors = ["srinivas-644 <srinivas.r@surya-soft.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbdate = {path = "../../../hdfc/libraries/RBDate"}
sdb_day_convention = { path = "../../../hdfc/libraries/sdb_day_convention" }
