[package]
name = "cf_cap_floor_reg_nd"
version = "1.0.2337"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]

[dependencies]
clap = "3.0.14"
sdb_io = {path = "../../../libraries/sdb_io"}
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.8.1"
slog-async = "2.7.0"
protobuf = { version = "2.27.1", features = ["with-bytes"] }
rbdate = { path = "../../../libraries/RBDate" }
health_report = { path = "../../../libraries/health_report" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
