#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub cod_acc_no: String,
    pub cod_cc_brn: String,
    pub cod_prod: String,
    pub bal_book: String,
    pub bal_book_lcy: String,
    pub amt_od_lmt: String,
    pub amt_od_lmt_lcy: String,
    pub cod_cust: String,
    pub cod_acc_title: String,
    pub dt_open_acc: String,
    pub cod_int_accr_bas: String,
    pub freq_int_accr: String,
    pub dt_acc_close: String,
    pub cod_collat_id: String,
    pub collat_desc: String,
    pub as_of_dt: String,
    pub cost_cntr: String,
    pub gl_acc_no: String,
    pub rt_flg: String,
    pub inst: String,
    pub crnt_book_bal: String,
    pub acrl_basis: String,
    pub int_rt: String,
    pub div: String,
    pub alm_line: String,
    pub ia_llg: String,
    pub balm_llg: String,
    pub mis1: String,
    pub npa_flg: String,
    pub benchmark: String,
    pub rep_freq: String,
    pub nxt_rep_dt: String,
    pub lst_rep_dt: String,
    pub cust_typ: String,
    pub country: String,
    pub bm_id_lookup: String,
    pub alm_concat: String,
    pub mis2: String,
    pub der_int_rate: String,
    pub benchmark_rate: String,
    pub spread: String,
    pub fully_floating_flag: String,
    pub b1: String,
    pub b2: String,
    pub b3: String,
}

impl InputAccount {
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|\
                {}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.cod_acc_no,
            self.cod_cc_brn,
            self.cod_prod,
            self.bal_book,
            self.bal_book_lcy,
            self.amt_od_lmt,
            self.amt_od_lmt_lcy,
            self.cod_cust,
            self.cod_acc_title,
            self.dt_open_acc,
            self.cod_int_accr_bas,
            self.freq_int_accr,
            self.dt_acc_close,
            self.cod_collat_id,
            self.collat_desc,
            self.as_of_dt,
            self.cost_cntr,
            self.gl_acc_no,
            self.rt_flg,
            self.inst,
            self.crnt_book_bal,
            self.acrl_basis,
            self.int_rt,
            self.div,
            self.alm_line,
            self.ia_llg,
            self.balm_llg,
            self.mis1,
            self.npa_flg,
            self.benchmark,
            self.rep_freq,
            self.nxt_rep_dt,
            self.lst_rep_dt,
            self.cust_typ,
            self.country,
            self.bm_id_lookup,
        )
    }
}
