[package]
name = "ftp_override"
version = "1.0.4137"
authors = ["Bhargavi052 <bhargavi.n@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
clap = "2.31.2"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
libmath = "0.2.1"
