[package]
name = "ucic_report_1"
version = "1.2.4638"
authors = ["Sachin Mulgir <sachin.m@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.81"
clap = "3.1.18"
health_report = {path = "../../../../libraries/health_report"}
rbdate = { path = "../../../../libraries/RBDate" }
sdb_io = { path = "../../../../libraries/sdb_io"}
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
serde = "1.0.160"
serde_derive = "1.0"
cond_utils = "0.1.0"
chrono = "0.4.24"
