[package]
name = "pp_cc_emi"
version = "1.0.3313"
authors = ["Ankur Gangwar <ankur.g@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
health_report = {path = "../../../../hdfc/libraries/health_report"}
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io"}
clap = "3.1.18"
calamine = "0.19.1"
