[package]
name = "non_equity_bond"
version = "1.0.1"
authors = ["srinivas-644 <srinivas.r@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
calamine = "0.24.0"
slog-term = "2.4.0"
slog-async = "2.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
csv = "1.1.1"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
health_report = { path = "../../libraries/health_report" }
