[package]
name = "pp_cc_non_emi"
version = "1.0.3314"
authors = ["ravindar-01<ravindar.sr@surya-soft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.81"
clap = "3.1.18"
health_report = {path = "../../../../../SuperDB-Batch/hdfc/libraries/health_report"}
rbdate = { path = "../../../../../SuperDB-Batch/hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../../SuperDB-Batch/hdfc/libraries/sdb_io"}
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
calamine = "0.18.0"
hashbrown = "0.12.1"
base64 = "0.13.0"
chrono = "0.4.22"
