[package]
name = "tenor_wise_dist"
version = "1.0.2289"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.3"
health_report = {path = "../../../libraries/health_report"}
protobuf = { version = "2.27.1", features = ["with-bytes"] }
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
