use cashflow_derivator::account_reader::input_account::InputAccount;
use cashflow_derivator::account_with_cashflows::Cashflow;
use rbdate::{timestamp, NaiveDate};

pub fn derive_cashflows(as_on_date: NaiveDate, account: &InputAccount) -> Vec<Cashflow> {
    let mut cashflows = Vec::new();
    let default_emi_date = NaiveDate::parse_from_str("31-12-1999", "%d-%m-%Y").unwrap();
    cashflows.push(new_cashflow(
        account.int_amt_1,
        account.prin_amt_1,
        account.emi_date_1.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_2,
        account.prin_amt_2,
        account.emi_date_2.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_3,
        account.prin_amt_3,
        account.emi_date_3.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_4,
        account.prin_amt_4,
        account.emi_date_4.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_5,
        account.prin_amt_5,
        account.emi_date_5.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_6,
        account.prin_amt_6,
        account.emi_date_6.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_7,
        account.prin_amt_7,
        account.emi_date_7.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_8,
        account.prin_amt_8,
        account.emi_date_8.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_9,
        account.prin_amt_9,
        account.emi_date_9.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_10,
        account.prin_amt_10,
        account.emi_date_10.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_11,
        account.prin_amt_11,
        account.emi_date_11.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_12,
        account.prin_amt_12,
        account.emi_date_12.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_13,
        account.prin_amt_13,
        account.emi_date_13.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_14,
        account.prin_amt_14,
        account.emi_date_14.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_15,
        account.prin_amt_15,
        account.emi_date_15.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_16,
        account.prin_amt_16,
        account.emi_date_16.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_17,
        account.prin_amt_17,
        account.emi_date_17.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_18,
        account.prin_amt_18,
        account.emi_date_18.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_19,
        account.prin_amt_19,
        account.emi_date_19.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_20,
        account.prin_amt_20,
        account.emi_date_20.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_21,
        account.prin_amt_21,
        account.emi_date_21.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_22,
        account.prin_amt_22,
        account.emi_date_22.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_23,
        account.prin_amt_23,
        account.emi_date_23.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_24,
        account.prin_amt_24,
        account.emi_date_24.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_25,
        account.prin_amt_25,
        account.emi_date_25.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_26,
        account.prin_amt_26,
        account.emi_date_26.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_27,
        account.prin_amt_27,
        account.emi_date_27.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_28,
        account.prin_amt_28,
        account.emi_date_28.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_29,
        account.prin_amt_29,
        account.emi_date_29.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_30,
        account.prin_amt_30,
        account.emi_date_30.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_31,
        account.prin_amt_31,
        account.emi_date_31.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_32,
        account.prin_amt_32,
        account.emi_date_32.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_33,
        account.prin_amt_33,
        account.emi_date_33.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_34,
        account.prin_amt_34,
        account.emi_date_34.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_35,
        account.prin_amt_35,
        account.emi_date_35.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_36,
        account.prin_amt_36,
        account.emi_date_36.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_37,
        account.prin_amt_37,
        account.emi_date_37.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_38,
        account.prin_amt_38,
        account.emi_date_38.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_39,
        account.prin_amt_39,
        account.emi_date_39.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_40,
        account.prin_amt_40,
        account.emi_date_40.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_41,
        account.prin_amt_41,
        account.emi_date_41.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_42,
        account.prin_amt_42,
        account.emi_date_42.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_43,
        account.prin_amt_43,
        account.emi_date_43.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_44,
        account.prin_amt_44,
        account.emi_date_44.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_45,
        account.prin_amt_45,
        account.emi_date_45.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_46,
        account.prin_amt_46,
        account.emi_date_46.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_47,
        account.prin_amt_47,
        account.emi_date_47.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_48,
        account.prin_amt_48,
        account.emi_date_48.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_49,
        account.prin_amt_49,
        account.emi_date_49.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_50,
        account.prin_amt_50,
        account.emi_date_50.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_51,
        account.prin_amt_51,
        account.emi_date_51.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_52,
        account.prin_amt_52,
        account.emi_date_52.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_53,
        account.prin_amt_53,
        account.emi_date_53.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_54,
        account.prin_amt_54,
        account.emi_date_54.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_55,
        account.prin_amt_55,
        account.emi_date_55.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_56,
        account.prin_amt_56,
        account.emi_date_56.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_57,
        account.prin_amt_57,
        account.emi_date_57.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_58,
        account.prin_amt_58,
        account.emi_date_58.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_59,
        account.prin_amt_59,
        account.emi_date_59.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_60,
        account.prin_amt_60,
        account.emi_date_60.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_61,
        account.prin_amt_61,
        account.emi_date_61.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_62,
        account.prin_amt_62,
        account.emi_date_62.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_63,
        account.prin_amt_63,
        account.emi_date_63.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_64,
        account.prin_amt_64,
        account.emi_date_64.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_65,
        account.prin_amt_65,
        account.emi_date_65.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_66,
        account.prin_amt_66,
        account.emi_date_66.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_67,
        account.prin_amt_67,
        account.emi_date_67.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_68,
        account.prin_amt_68,
        account.emi_date_68.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_69,
        account.prin_amt_69,
        account.emi_date_69.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_70,
        account.prin_amt_70,
        account.emi_date_70.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_71,
        account.prin_amt_71,
        account.emi_date_71.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_72,
        account.prin_amt_72,
        account.emi_date_72.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_73,
        account.prin_amt_73,
        account.emi_date_73.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_74,
        account.prin_amt_74,
        account.emi_date_74.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_75,
        account.prin_amt_75,
        account.emi_date_75.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_76,
        account.prin_amt_76,
        account.emi_date_76.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_77,
        account.prin_amt_77,
        account.emi_date_77.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_78,
        account.prin_amt_78,
        account.emi_date_78.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_79,
        account.prin_amt_79,
        account.emi_date_79.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_80,
        account.prin_amt_80,
        account.emi_date_80.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_81,
        account.prin_amt_81,
        account.emi_date_81.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_82,
        account.prin_amt_82,
        account.emi_date_82.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_83,
        account.prin_amt_83,
        account.emi_date_83.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_84,
        account.prin_amt_84,
        account.emi_date_84.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_85,
        account.prin_amt_85,
        account.emi_date_85.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_86,
        account.prin_amt_86,
        account.emi_date_86.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_87,
        account.prin_amt_87,
        account.emi_date_87.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_88,
        account.prin_amt_88,
        account.emi_date_88.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_89,
        account.prin_amt_89,
        account.emi_date_89.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_90,
        account.prin_amt_90,
        account.emi_date_90.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_91,
        account.prin_amt_91,
        account.emi_date_91.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_92,
        account.prin_amt_92,
        account.emi_date_92.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_93,
        account.prin_amt_93,
        account.emi_date_93.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_94,
        account.prin_amt_94,
        account.emi_date_94.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_95,
        account.prin_amt_95,
        account.emi_date_95.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_96,
        account.prin_amt_96,
        account.emi_date_96.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_97,
        account.prin_amt_97,
        account.emi_date_97.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_98,
        account.prin_amt_98,
        account.emi_date_98.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_99,
        account.prin_amt_99,
        account.emi_date_99.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_100,
        account.prin_amt_100,
        account.emi_date_100.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_101,
        account.prin_amt_101,
        account.emi_date_101.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_102,
        account.prin_amt_102,
        account.emi_date_102.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_103,
        account.prin_amt_103,
        account.emi_date_103.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_104,
        account.prin_amt_104,
        account.emi_date_104.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_105,
        account.prin_amt_105,
        account.emi_date_105.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_106,
        account.prin_amt_106,
        account.emi_date_106.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_107,
        account.prin_amt_107,
        account.emi_date_107.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_108,
        account.prin_amt_108,
        account.emi_date_108.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_109,
        account.prin_amt_109,
        account.emi_date_109.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_110,
        account.prin_amt_110,
        account.emi_date_110.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_111,
        account.prin_amt_111,
        account.emi_date_111.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_112,
        account.prin_amt_112,
        account.emi_date_112.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_113,
        account.prin_amt_113,
        account.emi_date_113.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_114,
        account.prin_amt_114,
        account.emi_date_114.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_115,
        account.prin_amt_115,
        account.emi_date_115.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_116,
        account.prin_amt_116,
        account.emi_date_116.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_117,
        account.prin_amt_117,
        account.emi_date_117.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_118,
        account.prin_amt_118,
        account.emi_date_118.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_119,
        account.prin_amt_119,
        account.emi_date_119.unwrap_or(default_emi_date),
        as_on_date,
    ));
    cashflows.push(new_cashflow(
        account.int_amt_120,
        account.prin_amt_120,
        account.emi_date_120.unwrap_or(default_emi_date),
        as_on_date,
    ));

    cashflows
}

fn new_cashflow(i_a: f64, p_a: f64, date: NaiveDate, as_on: NaiveDate) -> Cashflow {
    let mut cf = Cashflow::new();
    cf.set_prin_amt(p_a);
    cf.set_int_amt(i_a);
    cf.set_cf_date(timestamp(date) + timestamp(as_on));

    cf
}
