[package]
name = "pp_top_n_deposits"
version = "1.0.0"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
clap = "2.33.0"
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.2"
rbdate = { path = "../../hdfc/libraries/RBDate" }
sdb_io ={path = "../../hdfc/libraries/sdb_io" }
serde_json = "1.0.44"
serde_derive = "1.0.104"
serde = "1.0.104"
health_report={path="../../hdfc/libraries/health_report"}
protobuf = { version = "~2.0", features = ["with-bytes"] }
sdb_dyn_proto_rdr = { path = "../../hdfc/libraries/sdb_dyn_proto_rdr" }
