[package]
name = "monthly_average_balance_casa"
version = "1.0.2708"
authors = ["Saurabh Singh <saurabh.s@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
rbdate = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/sdb_io" }
health_report = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/health_report" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
float-cmp = "0.4.0"
calamine = "0.18.0"
