[package]
name = "corp-loans"
version = "1.0.2558"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.19"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
health_report = { path = "../../../hdfc/libraries/health_report" }
