#[derive(Debug, Default)]
pub struct InputAccount {
    pub deal_no: String,
    pub deal_date: String,
    pub value_dt_1st_leg: String,
    pub deal_time: String,
    pub nature: String,
    pub deal_stat: String,
    pub deal_type: String,
    pub slr_typ: String,
    pub security: String,
    pub category: String,
    pub sub_category: String,
    pub desk: String,
    pub portfolio: String,
    pub accounting_section: String,
    pub counterparty: String,
    pub counterparty_full_name: String,
    pub currency: String,
    pub face_val: String,
    pub haircut_margin: String,
    pub book_val: String,
    pub repo_rate: String,
    pub ytm: String,
    pub value_dt: String,
    pub price: String,
    pub hold_rate: String,
    pub holding_book_value: String,
    pub settle_amt_1st_leg: String,
    pub accrued_interest: String,
    pub repo_interest: String,
    pub settle_amt_2nd_leg: String,
    pub brokerage: String,
    pub broker: String,
    pub dealer_id: String,
    pub dealer_name: String,
    pub authoriser: String,
    pub auth_dt: String,
    pub auth_time: String,
    pub remarks: String,
    pub nds_entry_time: String,
    pub dvpiii: String,
    pub entity: String,
    pub bank_non_bank: String,
    pub air_aip: String,
}

impl InputAccount {
    pub fn new(fields: &Vec<&str>) -> Self {
        InputAccount {
            deal_no: fields[0].to_string(),
            deal_date: fields[1].to_string(),
            value_dt_1st_leg: fields[2].to_string(),
            deal_time: fields[3].to_string(),
            nature: fields[4].to_string(),
            deal_stat: fields[5].to_string(),
            deal_type: fields[6].to_string(),
            slr_typ: fields[7].to_string(),
            security: fields[8].to_string(),
            category: fields[9].to_string(),
            sub_category: fields[10].to_string(),
            desk: fields[11].to_string(),
            portfolio: fields[12].to_string(),
            accounting_section: fields[13].to_string(),
            counterparty: fields[14].to_string(),
            counterparty_full_name: fields[15].to_string(),
            currency: fields[16].to_string(),
            face_val: fields[17].to_string(),
            haircut_margin: fields[18].to_string(),
            book_val: fields[19].to_string(),
            repo_rate: fields[20].to_string(),
            ytm: fields[21].to_string(),
            value_dt: fields[22].to_string(),
            price: fields[23].to_string(),
            hold_rate: fields[24].to_string(),
            holding_book_value: fields[25].to_string(),
            settle_amt_1st_leg: fields[26].to_string(),
            accrued_interest: fields[27].to_string(),
            repo_interest: fields[28].to_string(),
            settle_amt_2nd_leg: fields[29].to_string(),
            brokerage: fields[30].to_string(),
            broker: fields[31].to_string(),
            dealer_id: fields[32].to_string(),
            dealer_name: fields[33].to_string(),
            authoriser: fields[34].to_string(),
            auth_dt: fields[35].to_string(),
            auth_time: fields[36].to_string(),
            remarks: fields[37].to_string(),
            nds_entry_time: fields[38].to_string(),
            dvpiii: fields[39].to_string(),
            entity: fields[40].to_string(),
            bank_non_bank: fields[41].to_string(),
            air_aip: fields[42].to_string(),
        }
    }
}
