[package]
name = "npa_splitter"
version = "1.0.0"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../../hdfc/libraries/RBDate" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../libraries/sdb_agg_rules" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
integer-encoding = "1.1.5"
