OPTIONS (SKIP=1, silent=feedback)
LOAD DATA
INFILE '*' "STR '\n'"
TRUNCATE
INTO TABLE Fin_Loans_Cashflows FIELDS TERMINATED BY '~#~'
 TRAILING NULLCOLS 
(
ACCOUNT_NUMBER,
INTEREST_AMOUNT,
PRINCIPLE_AMOUNT,
CASHFLOW_DATE date "dd/mm/yyyy"
)
