[package]
name = "cf_gl_npa"
version = "0.1.0"
authors = ["Tarun Jaiswal <tarun.j@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
clap = "2.33.0"
protobuf = { version = "~2.0", features = ["with-bytes"] }
