[package]
name = "health_report"
version = "1.1.2657"
authors = ["sougata bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
sdb_io = { path = "../sdb_io" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
