[package]
name = "group_by_aggregator"
version = "1.0.4765"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
sdb_agg_rules = { path = "../../../surya/libraries/sdb_agg_rules" }
slog-term = "2.4.0"
slog-async = "2.3.0"
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
sdb_agg_rules_txt = { path = "../../../surya/libraries/sdb_agg_rules_txt"}
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
health_report = { path = "../../../hdfc/libraries/health_report" }
calamine = "0.18.0"
libmath = "0.2.1"

