[package]
name = "cf_ftp_loans"
version = "1.0.3887"
authors = ["Janani <janani.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
chrono = "0.4"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
protobuf = { version = "2.15.0", features = ["with-bytes"] }
health_report = { path = "../../../../hdfc/libraries/health_report" }