[package]
name = "ftp-rd-bal-aggr"
version = "0.1.0"
authors = ["kavya"]

[dependencies]
clap="2.31.2"
sdb_dyn_proto_rdr = { path = "../../../libraries/sdb_dyn_proto_rdr" }
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
sdb_io ={path = "../../../libraries/sdb_io" }
slog-term = "2.4.0"
slog-async = "2.3.0"
chrono = "0.4"
rbconcurrency = { path = "../../../libraries/RBConcurrency" }
rbdate = { path = "../../../libraries/RBDate" }
health_report = { path = "../../../libraries/health_report" }
protobuf = { version = "~2.0", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
