#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub as_on: String,
    pub acc_no: String,
    pub cust_name: String,
    pub client_id: String,
    pub tl_limit: String,
    pub ccod_limit: String,
    pub pbg_limit: String,
    pub fbg_limit: String,
    pub loc_limit: String,
    pub bliab_bill_limit: String,
    pub tl_blnc: String,
    pub ccod_blnc: String,
    pub pbg_blnc: String,
    pub fbg_blnc: String,
    pub loc_blnc: String,
    pub bliab_bill_blnc: String,
    pub tl_ualimit: String,
    pub ccod_ualimit: String,
    pub pbg_ualimit: String,
    pub fbg_ualimit: String,
    pub loc_ualimit: String,
    pub bliab_bill_ualimit: String,
    pub tl_dep: String,
    pub ccod_dep: String,
    pub pbg_dep: String,
    pub fbg_dep: String,
    pub loc_dep: String,
    pub bliab_bill_dep: String,
    pub tl_cr_eq: String,
    pub ccod_cr_eq: String,
    pub pbg_cr_eq: String,
    pub fbg_cr_eq: String,
    pub loc_cr_eq: String,
    pub bliab_bill_cr_eq: String,
    pub client_type: String,
    pub ext_rating: String,
    pub asset_code: String,
    pub bsr: String,
    pub maturity_dt: String,
}

impl InputAccount {
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.as_on,
            self.acc_no,
            self.cust_name,
            self.client_id,
            self.tl_limit,
            self.ccod_limit,
            self.pbg_limit,
            self.fbg_limit,
            self.loc_limit,
            self.bliab_bill_limit,
            self.tl_blnc,
            self.ccod_blnc,
            self.pbg_blnc,
            self.fbg_blnc,
            self.loc_blnc,
            self.bliab_bill_blnc,
            self.tl_ualimit,
            self.ccod_ualimit,
            self.pbg_ualimit,
            self.fbg_ualimit,
            self.loc_ualimit,
            self.bliab_bill_ualimit,
            self.tl_dep,
            self.ccod_dep,
            self.pbg_dep,
            self.fbg_dep,
            self.loc_dep,
            self.bliab_bill_dep,
            self.tl_cr_eq,
            self.ccod_cr_eq,
            self.pbg_cr_eq,
            self.fbg_cr_eq,
            self.loc_cr_eq,
            self.bliab_bill_cr_eq,
            self.client_type,
            self.ext_rating,
            self.asset_code,
            self.bsr,
        )
    }
}
