[package]
name = "lien_summ_rep"
version = "1.0.2352"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
sdb_dyn_proto_rdr = { path = "../../libraries/sdb_dyn_proto_rdr" }
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
slog-term = "2.8.1"
slog-async = "2.7.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.19"
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
health_report = { path = "../../libraries/health_report" }
