[package]
name = "lien"
version = "1.0.4103"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
calamine = "0.16.1"
float-cmp = "0.4.0"
protobuf = { version = "~2.0", features = ["with-bytes"] }
