[package]
name = "lcr-classification-merger"
version = "1.0.0"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
sdb_dyn_proto_rdr = { path = "../../../libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../libraries/sdb_agg_rules" }
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
health_report = { path = "../../../libraries/health_report" }
calamine = "0.18.0"
