#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub account_id: String,
    pub outstanding_bal: String,
    pub currency: String,
    pub start_date: String,
    pub maturity_date: String,
    pub int_rate: String,
    pub int_rate_classification: String,
    pub benchmark: String,
    pub repricing_frequency: String,
    pub last_repr_date: String,
    pub next_repr_date: String,
    pub coupon_payment_start_date: String,
    pub coupon_payment_frequency: String,
    pub cust_constitution_code: String,
    pub instrument: String,
    pub counter_party_id: String,
    pub counter_party_name: String,
    pub counter_party_type: String,
    pub customer_id: String,
    pub customer_name: String,
    pub product_code: String,
    pub account_type: String,
    pub gl: String,
    pub rate_flag: String,
    pub branch: String,
    pub rm: String,
    pub group_code: String,
    pub monthly_avg_bal: String,
    pub aorl: String,
    pub rl1: String,
    pub rl2: String,
    pub rl3: String,
    pub tenor: String,
    pub total_interest_amount: String,
    pub total_principal_amount: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            account_id: "account_id".to_string(),
            outstanding_bal: "outstanding_bal".to_string(),
            currency: "currency".to_string(),
            start_date: "start_date".to_string(),
            maturity_date: "maturity_date".to_string(),
            int_rate: "int_rate".to_string(),
            int_rate_classification: "int_rate_classification".to_string(),
            benchmark: "benchmark".to_string(),
            repricing_frequency: "repricing_frequency".to_string(),
            last_repr_date: "last_repr_date".to_string(),
            next_repr_date: "next_repr_date".to_string(),
            coupon_payment_start_date: "coupon_payment_start_date".to_string(),
            coupon_payment_frequency: "coupon_payment_frequency".to_string(),
            cust_constitution_code: "cust_constitution_code".to_string(),
            instrument: "instrument".to_string(),
            counter_party_id: "counter_party_id".to_string(),
            counter_party_name: "counter_party_name".to_string(),
            counter_party_type: "counter_party_type".to_string(),
            customer_id: "customer_id".to_string(),
            customer_name: "customer_name".to_string(),
            product_code: "product_code".to_string(),
            account_type: "account_type".to_string(),
            gl: "gl".to_string(),
            rate_flag: "rate_flag".to_string(),
            branch: "branch".to_string(),
            rm: "rm".to_string(),
            group_code: "group_code".to_string(),
            monthly_avg_bal: "monthly_avg_bal".to_string(),
            aorl: "aorl".to_string(),
            rl1: "rl1".to_string(),
            rl2: "rl2".to_string(),
            rl3: "rl3".to_string(),
            tenor: "tenor".to_string(),
            total_interest_amount: "total_interest_amount".to_string(),
            total_principal_amount: "total_principal_amount".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
