[package]
name = "pre_mature_ftp_stamper"
version = "1.0.4108"
authors = ["Saurabh Singh <saurabh.s@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_day_convention = { path = "../../../../hdfc/libraries/sdb_day_convention" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io"}
health_report = { path = "../../../../hdfc/libraries/health_report" }
clap = "2.31.2"
calamine = "0.18.0"
chrono = "0.4.19"
