[package]
name = "pp_lien"
version = "1.0.4117"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../../hdfc/libraries/health_report" }
clap = "3.1.18"
csv = "1.2.0"
serde = "1.0.152"
serde_derive = "1.0.152"
