CREATE TABLE FCY_IRS_SWAP_MASTER
(
Entity VARCHAR2(128),
TradeId NUMERIC(24),
Contractid NUMERIC(24),
StructureIdLinkId NUMERIC(24),
ComponentTypology VARCHAR2(128),
PackageTypology VARCHAR2(128),
ContractTypology VARCHAR2(128),
ContractUsage VARCHAR2(128),
Desk VARCHAR2(128),
Book VARCHAR2(128),
Folder VARCHAR2(128),
TradingBanking VARCHAR2(128),
InternalExternal VARCHAR2(128),
CounterpartyGroupCode VARCHAR2(128),
CounterpartyParentCode VARCHAR2(128),
CounterpartyChildCode VARCHAR2(128),
CounterpartyName VARCHAR2(128),
TradeDate DATE NULL,
StartDate DATE NULL,
EndDate DATE NULL,
DealCurrency VARCHAR2(128),
OriginalNotional NUMERIC(24),
OriginalNotionalinINR NUMERIC(24),
RecCurrentNotional NUMERIC(24),
RecCurrentNotionalinINR NUMERIC(24),
PayCurrentNotional NUMERIC(24),
PayCurrentNotionalinINR NUMERIC(24),
ContingentNotional NUMERIC(24),
DealSide VARCHAR2(128),
PayLegIndex VARCHAR2(128),
PayIntRate NUMERIC(24),
SpreadPayleg NUMERIC(24),
RecLegIndex VARCHAR2(128),
RecIntRate NUMERIC(24),
SpreadRecleg NUMERIC(24),
PaySideAccrual NUMERIC(24),
PaySideMTM NUMERIC(24),
PaySideGMTM NUMERIC(24),
RecSideAccrual NUMERIC(24),
RecSideMTM NUMERIC(24),
RecSideGMTM NUMERIC(24),
NetAccrualinINR NUMERIC(24),
NetAccrualinUSD NUMERIC(24),
FutureCashProceedsCurrency VARCHAR2(128),
FutureCashProceeds NUMERIC(24),
FutureCashProceedsINR NUMERIC(24),
NETMTM NUMERIC(24),
NETMTMinINR NUMERIC(24),
NETMTMinUSD NUMERIC(24),
NETGMTMinINR NUMERIC(24),
NETGMTMinUSD NUMERIC(24),
NetBCVAadjustedGMTMinINR NUMERIC(24),
PaySidePV01inINR NUMERIC(24),
RecSidePV01inINR NUMERIC(24),
NetPV01inINR NUMERIC(24),
PaySideModifiedDuration NUMERIC(24),
ReceiveSideModifiedDuration NUMERIC(24),
ModifiedDurationofthedeal NUMERIC(24),
CVA NUMERIC(24),
DVA NUMERIC(24),
BCVA NUMERIC(24),
ExchangeRate NUMERIC(24),
PayResetDate DATE NULL,
RecResetDate DATE NULL,
PayPaymentDate DATE NULL,
RecPaymentDate DATE NULL,
BankOrNonBank VARCHAR2(128),
IndexRecLeg VARCHAR2(128),
IndexPayLeg VARCHAR2(128),
DayCountConventionleg1 VARCHAR2(128),
DayCountConventionleg2 VARCHAR2(128),
OriginalTenor NUMERIC(24),
ResidualTenor NUMERIC(24),
PayResetFrequency VARCHAR2(128),
RecResetFrequency VARCHAR2(128),
PayPaymentFrequency VARCHAR2(128),
RecPaymentFrequency VARCHAR2(128),
UnderlyingPP VARCHAR2(128),
DealStatus VARCHAR2(128),
InputID VARCHAR2(128),
AuthoriserID VARCHAR2(128),
Comment1 VARCHAR2(128)
);
