#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub account_id: String,
    pub sec_id: String,
    pub product: String,
    pub product_type: String,
    pub face_amt: String,
    pub outstanding_bal: String,
    pub currency: String,
    pub cmne: String,
    pub sn: String,
    pub c_type: String,
    pub start_date: String,
    pub maturity_date: String,
    pub repo_rate: String,
    pub int_calc_type: String,
    pub spread: String,
    pub benchmark: String,
    pub last_repr_date: String,
    pub next_repr_date: String,
    pub int_rate: String,
    pub rate_flag: String,
    pub product_code: String,
    pub customer_id: String,
    pub branch: String,
    pub rm: String,
    pub department: String,
    pub gl: String,
    pub customer_name: String,
    pub monthly_avg_bal: String,
    pub aorl: String,
    pub rl1: String,
    pub rl2: String,
    pub rl3: String,
    pub total_interest_amount: String,
    pub total_principal_amount: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            account_id: "account_id".to_string(),
            sec_id: "sec_id".to_string(),
            product: "product".to_string(),
            product_type: "product_type".to_string(),
            face_amt: "face_amt".to_string(),
            outstanding_bal: "outstanding_bal".to_string(),
            currency: "currency".to_string(),
            cmne: "cmne".to_string(),
            sn: "sn".to_string(),
            c_type: "c_type".to_string(),
            start_date: "start_date".to_string(),
            maturity_date: "maturity_date".to_string(),
            repo_rate: "repo_rate".to_string(),
            int_calc_type: "int_calc_type".to_string(),
            spread: "spread".to_string(),
            benchmark: "benchmark".to_string(),
            last_repr_date: "last_repr_date".to_string(),
            next_repr_date: "next_repr_date".to_string(),
            int_rate: "int_rate".to_string(),
            rate_flag: "rate_flag".to_string(),
            product_code: "product_code".to_string(),
            customer_id: "customer_id".to_string(),
            branch: "branch".to_string(),
            rm: "rm".to_string(),
            department: "department".to_string(),
            gl: "gl".to_string(),
            customer_name: "customer_name".to_string(),
            monthly_avg_bal: "monthly_avg_bal".to_string(),
            aorl: "aorl".to_string(),
            rl1: "rl1".to_string(),
            rl2: "rl2".to_string(),
            rl3: "rl3".to_string(),
            total_interest_amount: "total_interest_amount".to_string(),
            total_principal_amount: "total_principal_amount".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
