#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub bond_issuance: String,
    pub isin: String,
    pub issuance_dt: String,
    pub branch_entity: String,
    pub desk: String,
    pub portfolio_type: String,
    pub category: String,
    pub security_type: String,
    pub slrnon_slr: String,
    pub short_name: String,
    pub secured_unsecured: String,
    pub rt: String,
    pub nxt_call_dt: String,
    pub nxt_put_dt: String,
    pub agency: String,
    pub rating: String,
    pub agency_of_current_rating: String,
    pub listed_unlisted: String,
    pub mat_dt: String,
    pub conversion_rt_lcy: String,
    pub ccy: String,
    pub bv_after_amortisation: String,
    pub wap: String,
    pub laf_and_msf_ost_fv: String,
    pub laf_and_msf_ost_bv: String,
    pub reverse_laf_ost_fv: String,
    pub reverse_repo_ost_fv: String,
    pub collateral_placed_fv: String,
    pub encumbered_fv: String,
    pub encumbered_bv: String,
    pub ytm: String,
    pub basis: String,
    pub issue_country: String,
    pub domicile_country: String,
    pub category1: String,
    pub category2: String,
    pub category3: String,
    pub category4: String,
    pub industry_code: String,
    pub taxability: String,
    pub air_till_dt: String,
    pub modified_duration: String,
    pub int_coupontype: String,
    pub nxt_re_pricing_dt: String,
    pub sec_grp: String,
    pub sec_typ: String,
    pub sec_issuer: String,
    pub sec_guaranteed: String,
    pub mrkt: String,
    pub idx_label: String,
    pub bd_cat: String,
    pub bd_typ: String,
    pub lstd: String,
    pub npa: String,
    pub cf_dt: String,
    pub cf_int_amt: String,
    pub cf_prin_amt: String,
    pub bv_before_amort: String,
    pub fv: String,
}

impl InputAccount {
    pub fn to_string(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|\
             {}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|\
             {}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",
            self.bond_issuance,
            self.isin,
            self.issuance_dt,
            self.branch_entity,
            self.desk,
            self.portfolio_type,
            self.category,
            self.security_type,
            self.slrnon_slr,
            self.short_name,
            self.secured_unsecured,
            self.rt,
            self.nxt_call_dt,
            self.nxt_put_dt,
            self.agency,
            self.rating,
            self.agency_of_current_rating,
            self.listed_unlisted,
            self.mat_dt,
            self.conversion_rt_lcy,
            self.ccy,
            self.bv_after_amortisation,
            self.wap,
            self.laf_and_msf_ost_fv,
            self.laf_and_msf_ost_bv,
            self.reverse_laf_ost_fv,
            self.reverse_repo_ost_fv,
            self.collateral_placed_fv,
            self.encumbered_fv,
            self.encumbered_bv,
            self.ytm,
            self.basis,
            self.issue_country,
            self.domicile_country,
            self.category1,
            self.category2,
            self.category3,
            self.category4,
            self.industry_code,
            self.taxability,
            self.air_till_dt,
            self.modified_duration,
            self.int_coupontype,
            self.nxt_re_pricing_dt,
            self.sec_grp,
            self.sec_typ,
            self.sec_issuer,
            self.sec_guaranteed,
            self.mrkt,
            self.idx_label,
            self.bd_cat,
            self.bd_typ,
            self.lstd,
            self.npa,
            self.cf_dt,
            self.cf_int_amt,
            self.cf_prin_amt,
        )
    }
}
