[package]
name = "pp_opt_reg_nd"
version = "1.0.2325"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
sdb_dyn_proto_rdr = { path = "../../../libraries/sdb_dyn_proto_rdr" }
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
slog-term = "2.8.0"
slog-async = "2.7.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
health_report = { path = "../../../libraries/health_report" }
calamine = "0.18.0"
