[package]
name = "lcr_cust_bal_aggr_lcy"
version = "1.3.3707"
authors = ["shashank676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.32.0"
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
health_report = {path = "../../../../hdfc/libraries/health_report" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
