[package]
name = "pp_individual_loans"
version = "1.0.5447"
authors = ["srinivas-644 <srinivas.r@surya-soft.com>"]

[dependencies]
chrono = "0.4"
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../hdfc/libraries/health_report" }
sdb_cf_gen = { path = "../../../surya/libraries/sdb_cf_gen" }
calamine = "0.19.1"
