[package]
name = "pp_over_invst"
version = "0.1.0"
authors = ["Tarun Jaiswal <tarun.j@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
clap = "2.31.2"
calamine = "0.15.3"
