CREATE TABLE BIU_S2
(
COD_CUST VARCHAR(50),
SAL_TXN VARCHAR(5),
T4_FLAG VARCHAR(5),
TRANSX_FLAG_2_OTHERS VARCHAR(5),
CUSTOMER_TYPE VARCHAR(5),
NATURE_OF_BUS VARCHAR(20),
TXT_BUS_DESC VARCHAR(20),
);