#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub acc_no: String,
    pub acnts_internal_acnum: String,
    pub acnts_brn_cd: String,
    pub acnts_client_num: String,
    pub ucic: String,
    pub acnts_curr_cd: String,
    pub acnts_prod_cd: String,
    pub gl_cd: String,
    pub acnts_opening_dt: String,
    pub bal: String,
    pub bal_ccy: String,
    pub int_rt: String,
    pub int_type: String,
    pub int_bench: String,
    pub int_spread: String,
    pub last_reset_dt: String,
    pub next_reset_dt: String,
    pub reset_no_of_months: String,
    pub disbursal_amount: String,
    pub last_emi_dt: String,
    pub lm_exp: String,
    pub lim: String,
    pub lm_ccy: String,
    pub ext_rating_agency: String,
    pub ext_rating: String,
    pub int_rating: String,
    pub assetcd: String,
    pub prov_amt: String,
    pub prov_dt: String,
    pub constitn: String,
    pub as_on: String,
    pub loan_type: String,
    pub def_amt: String,
    pub def_dt: String,
    pub last_paid_emi_dt: String,
}

impl InputAccount {
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|\
             {}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.acc_no,
            self.acnts_internal_acnum,
            self.acnts_brn_cd,
            self.acnts_client_num,
            self.ucic,
            self.acnts_curr_cd,
            self.acnts_prod_cd,
            self.gl_cd,
            self.acnts_opening_dt,
            self.bal,
            self.bal_ccy,
            self.int_rt,
            self.int_type,
            self.int_bench,
            self.int_spread,
            self.last_reset_dt,
            self.next_reset_dt,
            self.reset_no_of_months,
            self.disbursal_amount,
            self.last_emi_dt,
            self.lm_exp,
            self.lim,
            self.lm_ccy,
            self.ext_rating_agency,
            self.ext_rating,
            self.int_rating,
            self.assetcd,
            self.prov_amt,
            self.prov_dt,
            self.constitn,
            self.loan_type,
            self.def_amt,
            self.def_dt,
            self.last_paid_emi_dt,
        )
    }

    pub fn print_td(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.acc_no,
            self.acnts_brn_cd,
            self.acnts_client_num,
            self.ucic,
            self.bal_ccy,
            self.acnts_prod_cd,
            self.gl_cd,
            "",
            self.acnts_opening_dt,
            "",
            self.bal,
            self.bal_ccy,
            "",
            "",
            "0",
            self.last_paid_emi_dt,
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            self.as_on,
            "",
            "",
            "",
            "",
            "",
        )
    }
}
