OPTIONS (SKIP=2, silent=feedback)
LOAD DATA
INFILE '*' "STR '\r\n'"
TRUNCATE
INTO TABLE OVER_LOANS_CASHFLOW FIELDS TERMINATED BY ','
 TRAILING NULLCOLS 
(
BRANCH,
CONTRACT_REF_NO,
USER_REF_NO,
PRODUCT,
PRODUCT_DESCRIPTION,
CUSTOMER_NAME1,
CIF_ID,
COMPONENT,
DUE_DATE DATE "MM/DD/YYYY",
CURRENCY_AMT_DUE,
AMOUNT_DUE,
AMOUNT_SETTLED,
INVOICE_NO,
CONTRACT_STATUS
)
