[package]
name = "merger_finnone_struct_loans"
version = "1.0.3138"
authors = ["Saurabh Singh <saurabh.s@surya-soft.com>"]

[dependencies]
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.2"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
clap = "2.33.0"
chrono = "0.4.10"
health_report = { path = "../../../libraries/health_report" }
serde = "1.0.104"
serde_derive = "1.0.104"
