[package]
name = "cf_reci_lend_automation"
version = "1.0.0"
authors = ["srinivas-644 <srinivas.r@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
protobuf = { version = "2.16.2", features = ["with-bytes"] }

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
