[package]
name = "sls-rpt"
version = "1.1.0"
authors = ["shashank676 <shashank.p@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.32.0"
chrono = "0.4"
health_report = {path = "../../../hdfc/libraries/health_report"}
protobuf = { version = "~2.0", features = ["with-bytes"] }
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io"}
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
