use sdb_io;
use serde_derive::*;
use serde_json;
use std::io::Read;

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AccFieldNames {
    pub deal_no: String,
    pub short_name: String,
    pub nxt_rep_dt: String,
    pub call_dt: String,
    pub put_dt: String,
    pub deal_dt: String,
    pub portfolio: String,
    pub deal_rt: String,
    pub org_face_val: String,
    pub os_face_val: String,
    pub org_cst_val: String,
    pub acrd_int: String,
    pub book_yield: String,
    pub int_basis: String,
    pub avg_os_vd: String,
    pub avg_os_dd: String,
    pub prin_amt: String,
    pub org_bal: String,
    pub coup_rt: String,
    pub nxt_coup_dt: String,
    pub gl: String,
    pub cf_dt: String,
    pub secu_desc: String,
    pub prod_desc: String,
    pub prod_cd: String,
    pub lst_coup_dt: String,
    pub call_dt1: String,
    pub coup_freq: String,
    pub val_dt: String,
    pub acrl_freq: String,
    pub lst_rep_dt: String,
    pub lst_put_dt: String,
    pub inst: String,
    pub org_term: String,
    pub acrl_basis: String,
    pub div: String,
    pub alm_line: String,
    pub ia_line: String,
    pub cmpnd_freq: String,
    pub nxt_cmpnd_dt: String,
    pub rt_chng_freq: String,
    pub rt_flg: String,
    pub rep_idx: String,
    pub nxt_pay_dt: String,
    pub prev_rep_dt: String,
    pub int_pay_freq: String,
    pub int_rt: String,
    pub port_typ: String,
    pub sec_grp: String,
    pub sec_type: String,
    pub sec_issuer: String,
    pub sec_guaranteed: String,
    pub mrkt: String,
    pub idx_label: String,
    pub bd_categ: String,
    pub bd_type: String,
    pub listed: String,
    pub npa_class: String,
    pub entity: String,
    pub desk: String,
    pub acc_sec_igaap: String,
    pub os_cv_before_amort: String,
    pub os_cv_after_amort: String,
    pub mat_dt: String,
    pub int_amt: String,
    pub flow_type: String,
    pub isin: String,
    pub org_tenor: String,
    pub rep_tenor: String,
    pub ftp_mat_dt: String,
    pub wap_igaap: String,
    pub ost_bal: String,
    pub contract_no: String,
    pub instr_id: String,
    pub parent_code: String,
    pub issuer_name: String,
    pub rating: String,
    pub tax_status: String,
    pub slr_nslr: String,
    pub deal_ytm: String,
    pub intr_app_freq: String,
    pub comp_freq: String,
    pub intr_prac: String,
    pub rate_spread: String,
    pub asset_class: String,
    pub intr_typ: String,
    pub sec_issuance_date: String,
    pub coupon: String,
    pub last_intr_date: String,
    pub next_intr_date: String,
    pub amort_till_date: String,
    pub tot_int_amt: String,
    pub tot_prin_amt: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn new_from_path(_path: &str) -> AccFieldNames {
        let mut file = sdb_io::open_file_read(_path).expect("Unable to open Required-Fields-File");
        let mut buf = String::new();
        file.read_to_string(&mut buf)
            .expect("Cannot read input as string from Req-Fields File");
        let req_fields: AccFieldNames =
            serde_json::from_str(&buf[..]).expect("Required-Fields-File was not well-formatted");
        req_fields
    }

    pub fn get_input_fields_names(_path: &str) -> AccFieldNames {
        let req_fields = Self::new_from_path(_path);
        AccFieldNames {
            deal_no: req_fields.deal_no.to_string(),
            short_name: req_fields.short_name.to_string(),
            nxt_rep_dt: req_fields.nxt_rep_dt.to_string(),
            call_dt: req_fields.call_dt.to_string(),
            put_dt: req_fields.put_dt.to_string(),
            deal_dt: req_fields.deal_dt.to_string(),
            portfolio: req_fields.portfolio.to_string(),
            deal_rt: req_fields.deal_rt.to_string(),
            org_face_val: req_fields.org_face_val.to_string(),
            os_face_val: req_fields.os_face_val.to_string(),
            org_cst_val: req_fields.org_cst_val.to_string(),
            acrd_int: req_fields.acrd_int.to_string(),
            book_yield: req_fields.book_yield.to_string(),
            int_basis: req_fields.int_basis.to_string(),
            avg_os_vd: req_fields.avg_os_vd.to_string(),
            avg_os_dd: req_fields.avg_os_dd.to_string(),
            prin_amt: req_fields.prin_amt.to_string(),
            org_bal: req_fields.org_bal.to_string(),
            coup_rt: req_fields.coup_rt.to_string(),
            nxt_coup_dt: req_fields.nxt_coup_dt.to_string(),
            gl: req_fields.gl.to_string(),
            cf_dt: req_fields.cf_dt.to_string(),
            secu_desc: req_fields.secu_desc.to_string(),
            prod_desc: req_fields.prod_desc.to_string(),
            prod_cd: req_fields.prod_cd.to_string(),
            lst_coup_dt: req_fields.lst_coup_dt.to_string(),
            call_dt1: req_fields.call_dt1.to_string(),
            coup_freq: req_fields.coup_freq.to_string(),
            val_dt: req_fields.val_dt.to_string(),
            acrl_freq: req_fields.acrl_freq.to_string(),
            lst_rep_dt: req_fields.lst_rep_dt.to_string(),
            lst_put_dt: req_fields.lst_put_dt.to_string(),
            inst: req_fields.inst.to_string(),
            org_term: req_fields.org_term.to_string(),
            acrl_basis: req_fields.acrl_basis.to_string(),
            div: req_fields.div.to_string(),
            alm_line: req_fields.alm_line.to_string(),
            ia_line: req_fields.ia_line.to_string(),
            cmpnd_freq: req_fields.cmpnd_freq.to_string(),
            nxt_cmpnd_dt: req_fields.nxt_cmpnd_dt.to_string(),
            rt_chng_freq: req_fields.rt_chng_freq.to_string(),
            rt_flg: req_fields.rt_flg.to_string(),
            rep_idx: req_fields.rep_idx.to_string(),
            nxt_pay_dt: req_fields.nxt_pay_dt.to_string(),
            prev_rep_dt: req_fields.prev_rep_dt.to_string(),
            int_pay_freq: req_fields.int_pay_freq.to_string(),
            int_rt: req_fields.int_rt.to_string(),
            port_typ: req_fields.port_typ.to_string(),
            sec_grp: req_fields.sec_grp.to_string(),
            sec_type: req_fields.sec_type.to_string(),
            sec_issuer: req_fields.sec_issuer.to_string(),
            sec_guaranteed: req_fields.sec_guaranteed.to_string(),
            mrkt: req_fields.mrkt.to_string(),
            idx_label: req_fields.idx_label.to_string(),
            bd_categ: req_fields.bd_categ.to_string(),
            bd_type: req_fields.bd_type.to_string(),
            listed: req_fields.listed.to_string(),
            npa_class: req_fields.npa_class.to_string(),
            entity: req_fields.entity.to_string(),
            desk: req_fields.desk.to_string(),
            acc_sec_igaap: req_fields.acc_sec_igaap.to_string(),
            os_cv_before_amort: req_fields.os_cv_before_amort.to_string(),
            os_cv_after_amort: req_fields.os_cv_after_amort.to_string(),
            mat_dt: req_fields.mat_dt.to_string(),
            int_amt: req_fields.int_amt.to_string(),
            flow_type: req_fields.flow_type.to_string(),
            isin: req_fields.isin.to_string(),
            org_tenor: req_fields.org_tenor.to_string(),
            rep_tenor: req_fields.rep_tenor.to_string(),
            ftp_mat_dt: req_fields.ftp_mat_dt.to_string(),
            wap_igaap: req_fields.wap_igaap.to_string(),
            ost_bal: req_fields.ost_bal.to_string(),
            contract_no: req_fields.contract_no.to_string(),
            instr_id: req_fields.instr_id.to_string(),
            parent_code: req_fields.parent_code.to_string(),
            issuer_name: req_fields.issuer_name.to_string(),
            rating: req_fields.rating.to_string(),
            tax_status: req_fields.tax_status.to_string(),
            slr_nslr: req_fields.slr_nslr.to_string(),
            deal_ytm: req_fields.deal_ytm.to_string(),
            intr_app_freq: req_fields.intr_app_freq.to_string(),
            comp_freq: req_fields.comp_freq.to_string(),
            intr_prac: req_fields.intr_prac.to_string(),
            rate_spread: req_fields.rate_spread.to_string(),
            asset_class: req_fields.asset_class.to_string(),
            intr_typ: req_fields.intr_typ.to_string(),
            sec_issuance_date: req_fields.sec_issuance_date.to_string(),
            coupon: req_fields.coupon.to_string(),
            last_intr_date: req_fields.last_intr_date.to_string(),
            next_intr_date: req_fields.next_intr_date.to_string(),
            amort_till_date: req_fields.amort_till_date.to_string(),
            tot_int_amt: req_fields.tot_int_amt.to_string(),
            tot_prin_amt: req_fields.tot_prin_amt.to_string(),
            cashflows: req_fields.cashflows.to_string(),
        }
    }
}
