[package]
name = "nsfr_file_splitter"
version = "1.0.4617"
authors = ["ravindar-01<ravindar.sr@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
clap = "2.31.2"
itertools = "0.9.0"
chrono = "0.4.6"
