OPTIONS (SKIP=1)
LOAD DATA
INFILE '../cashflows.csv' "STR '\r\n'"
TRUNCATE
INTO TABLE OVER_LOANS_CASHFLOW FIELDS TERMINATED BY ','
 TRAILING NULLCOLS 
(
REFERENCE,
COMPONENT,
DUE_DATE DATE,
AMOUNT_DUE,
AMOUNT_SETTLED
)
