// This file is generated by rust-protobuf 2.6.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct OutputAccount {
    // message fields
    pub as_on: i64,
    pub segment: ::std::string::String,
    pub sub_segment: ::std::string::String,
    pub member_id: ::std::string::String,
    pub member_name: ::std::string::String,
    pub cash: f64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OutputAccount {
    fn default() -> &'a OutputAccount {
        <OutputAccount as ::protobuf::Message>::default_instance()
    }
}

impl OutputAccount {
    pub fn new() -> OutputAccount {
        ::std::default::Default::default()
    }

    // int64 as_on = 1;


    pub fn get_as_on(&self) -> i64 {
        self.as_on
    }
    pub fn clear_as_on(&mut self) {
        self.as_on = 0;
    }

    // Param is passed by value, moved
    pub fn set_as_on(&mut self, v: i64) {
        self.as_on = v;
    }

    // string segment = 2;


    pub fn get_segment(&self) -> &str {
        &self.segment
    }
    pub fn clear_segment(&mut self) {
        self.segment.clear();
    }

    // Param is passed by value, moved
    pub fn set_segment(&mut self, v: ::std::string::String) {
        self.segment = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_segment(&mut self) -> &mut ::std::string::String {
        &mut self.segment
    }

    // Take field
    pub fn take_segment(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.segment, ::std::string::String::new())
    }

    // string sub_segment = 3;


    pub fn get_sub_segment(&self) -> &str {
        &self.sub_segment
    }
    pub fn clear_sub_segment(&mut self) {
        self.sub_segment.clear();
    }

    // Param is passed by value, moved
    pub fn set_sub_segment(&mut self, v: ::std::string::String) {
        self.sub_segment = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_sub_segment(&mut self) -> &mut ::std::string::String {
        &mut self.sub_segment
    }

    // Take field
    pub fn take_sub_segment(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.sub_segment, ::std::string::String::new())
    }

    // string member_id = 4;


    pub fn get_member_id(&self) -> &str {
        &self.member_id
    }
    pub fn clear_member_id(&mut self) {
        self.member_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_member_id(&mut self, v: ::std::string::String) {
        self.member_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_member_id(&mut self) -> &mut ::std::string::String {
        &mut self.member_id
    }

    // Take field
    pub fn take_member_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.member_id, ::std::string::String::new())
    }

    // string member_name = 5;


    pub fn get_member_name(&self) -> &str {
        &self.member_name
    }
    pub fn clear_member_name(&mut self) {
        self.member_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_member_name(&mut self, v: ::std::string::String) {
        self.member_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_member_name(&mut self) -> &mut ::std::string::String {
        &mut self.member_name
    }

    // Take field
    pub fn take_member_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.member_name, ::std::string::String::new())
    }

    // double cash = 6;


    pub fn get_cash(&self) -> f64 {
        self.cash
    }
    pub fn clear_cash(&mut self) {
        self.cash = 0.;
    }

    // Param is passed by value, moved
    pub fn set_cash(&mut self, v: f64) {
        self.cash = v;
    }
}

impl ::protobuf::Message for OutputAccount {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.as_on = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.segment)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.sub_segment)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.member_id)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.member_name)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.cash = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.as_on != 0 {
            my_size += ::protobuf::rt::value_size(1, self.as_on, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.segment.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.segment);
        }
        if !self.sub_segment.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.sub_segment);
        }
        if !self.member_id.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.member_id);
        }
        if !self.member_name.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.member_name);
        }
        if self.cash != 0. {
            my_size += 9;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.as_on != 0 {
            os.write_int64(1, self.as_on)?;
        }
        if !self.segment.is_empty() {
            os.write_string(2, &self.segment)?;
        }
        if !self.sub_segment.is_empty() {
            os.write_string(3, &self.sub_segment)?;
        }
        if !self.member_id.is_empty() {
            os.write_string(4, &self.member_id)?;
        }
        if !self.member_name.is_empty() {
            os.write_string(5, &self.member_name)?;
        }
        if self.cash != 0. {
            os.write_double(6, self.cash)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OutputAccount {
        OutputAccount::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "as_on",
                    |m: &OutputAccount| { &m.as_on },
                    |m: &mut OutputAccount| { &mut m.as_on },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "segment",
                    |m: &OutputAccount| { &m.segment },
                    |m: &mut OutputAccount| { &mut m.segment },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "sub_segment",
                    |m: &OutputAccount| { &m.sub_segment },
                    |m: &mut OutputAccount| { &mut m.sub_segment },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "member_id",
                    |m: &OutputAccount| { &m.member_id },
                    |m: &mut OutputAccount| { &mut m.member_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "member_name",
                    |m: &OutputAccount| { &m.member_name },
                    |m: &mut OutputAccount| { &mut m.member_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "cash",
                    |m: &OutputAccount| { &m.cash },
                    |m: &mut OutputAccount| { &mut m.cash },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<OutputAccount>(
                    "OutputAccount",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static OutputAccount {
        static mut instance: ::protobuf::lazy::Lazy<OutputAccount> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const OutputAccount,
        };
        unsafe {
            instance.get(OutputAccount::new)
        }
    }
}

impl ::protobuf::Clear for OutputAccount {
    fn clear(&mut self) {
        self.as_on = 0;
        self.segment.clear();
        self.sub_segment.clear();
        self.member_id.clear();
        self.member_name.clear();
        self.cash = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OutputAccount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OutputAccount {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ccsb_nsfr_caash_holding.proto\"\xb1\x01\n\rOutputAccount\x12\x13\n\
    \x05as_on\x18\x01\x20\x01(\x03R\x04asOn\x12\x18\n\x07segment\x18\x02\x20\
    \x01(\tR\x07segment\x12\x1f\n\x0bsub_segment\x18\x03\x20\x01(\tR\nsubSeg\
    ment\x12\x1b\n\tmember_id\x18\x04\x20\x01(\tR\x08memberId\x12\x1f\n\x0bm\
    ember_name\x18\x05\x20\x01(\tR\nmemberName\x12\x12\n\x04cash\x18\x06\x20\
    \x01(\x01R\x04cashb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
