#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub acc_no: String,
    pub br_cd: String,
    pub cust_no: String,
    pub ucc_id: String,
    pub ccy: String,
    pub produ: String,
    pub gl: String,
    pub gl_comp_portn: String,
    pub open_dt: String,
    pub effect_dt: String,
    pub os_bal: String,
    pub os_bal_cry: String,
    pub int_comp_type: String,
    pub comp_int_amt: String,
    pub int_rt: String,
    pub mat_dt: String,
    pub dep_amt: String,
    pub dep_amt_cry: String,
    pub int_amt: String,
    pub int_acrd: String,
    pub non_with_flag: String,
    pub notice_day: String,
    pub const_cd: String,
    pub const_desc: String,
}

impl InputAccount {
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.acc_no,
            self.br_cd,
            self.cust_no,
            self.ucc_id,
            self.ccy,
            self.produ,
            self.gl,
            self.gl_comp_portn,
            self.open_dt,
            self.effect_dt,
            self.os_bal,
            self.os_bal_cry,
            self.int_comp_type,
            self.comp_int_amt,
            self.int_rt,
            self.mat_dt,
            self.dep_amt,
            self.dep_amt_cry,
            self.int_amt,
            self.int_acrd,
            self.non_with_flag,
            self.notice_day,
            self.const_cd,
            self.const_desc,
        )
    }
}
