[package]
name = "sdb_agg_rules_txt"
version = "0.1.0"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
