  select
ISNULL(A1.reval_dt,'NA')		
+'|'+ISNULL(A1.deal_type,'NA')
+'|'+ISNULL(A1.deal_ref,'NA')
+'|'+ISNULL(A1.leg_id,'NA')
+'|'+ISNULL(A1.portfolio,'NA')
+'|'+ISNULL(A1.product,'NA')
+'|'+ISNULL(A1.counter_party,'NA')
+'|'+ISNULL(A1.buy_sell,'NA')
+'|'+ISNULL(A1.deal_dt,'NA')
+'|'+ISNULL(A1.val_dt,'NA')
+'|'+ISNULL(A1.ccy_1,'NA')
+'|'+ISNULL(A1.ccy_2,'NA')
+'|'+ISNULL(A1.deal_rt,'NA')
+'|'+ISNULL(A1.ccy1_amt,'NA')
+'|'+ISNULL(A1.crnct2_amt,'NA')
+'|'+ISNULL(A1.reval_rt,'NA')
+'|'+ISNULL(A1.reval_eqv,'NA')
+'|'+ISNULL(A1.actual_pl,'NA')
+'|'+ISNULL(A1.pnl_conversion_rt,'NA')
+'|'+ISNULL(A1.int_rt,'NA')
+'|'+ISNULL(A1.discounted_factor,'NA')
+'|'+ISNULL(A1.present_val_pl,'NA')
+'|'+ISNULL(A1.ccy1_spot_rt,'NA')
+'|'+ISNULL(A1.ccy2_spot_rt,'NA')
+'|'+ISNULL(A1.inr_eq_ccy1_spot_rt,'NA')
+'|'+ISNULL(A1.inr_eq_ccy2_spot_rt,'NA')
+'|'+ISNULL(A1.branch_code,'NA')
+'|'+ISNULL(A1.trsy_gl,'NA')
+'|'+ISNULL(C1.cf_typ,'Principal')
+'|'+ISNULL(C1.cf_amt,0)
+'|'+ISNULL(C1.cf_ccy,ISNULL(A1.ccy_1,'INR'))
+'|'+ISNULL(C1.cf_dt,'01-01-2099') as maturity_dt
from FXSpotData A1 left outer join FXSpotCF C1
ON A1.deal_ref=C1.deal_no
order by A1.deal_ref