[package]
name = "basel_deal_level"
version = "1.0.4755"
authors = ["srinivas-664 <srinivas.r@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
sdb_dyn_proto_rdr = { path = "../../../libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../../surya/libraries/sdb_agg_rules" }
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
float-cmp = "0.4.0"
