[package]
name = "significant_counterparty_deposits"
version = "1.0.1"
authors = ["Paris BS. <paris.bs@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
clap = "2.33.0"
slog = "2.5.2"
slog-async = "2.3.0"
slog-term = "2.4.2"
rbdate = { path = "../../../../libraries/RBDate" }
sdb_io ={path = "../../../../libraries/sdb_io" }
serde_json = "1.0.44"
serde_derive = "1.0.104"
serde = "1.0.104"
health_report={path="../../../../libraries/health_report"}
csv = "1.1.1"
