[package]
name = "cf_swaps_moc"
version = "1.1.4738"
authors = ["Tanuj Singh Rathore<tanuj.s@surya-soft.com>"]

[dependencies]

clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
protobuf = { version = "2.8.1", features = ["with-bytes"] }
serde ="1.0"
serde_json ="1.0"
serde_derive = "1.0"

rbdate = { path = "../../../../hdfc/libraries/RBDate/" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io/" }
health_report = { path = "../../../../hdfc/libraries/health_report/" }
calamine = "0.18.0"
sdb_day_convention = { path = "../../../libraries/sdb_day_convention" }
