  select
A1.portfolio_num
+'|'+ISNULL(A1.portfolio, 'NA')
+'|'+ISNULL(A1.security_name, 'NA')
+'|'+ISNULL(A1.maturity_dt, 'NA')
+'|'+ISNULL(A1.coupon, 'NA')
+'|'+ISNULL(A1.face_val_per_units, 'NA')
+'|'+ISNULL(A1.quantity, 'NA')
+'|'+ISNULL(A1.face_val, 'NA')
+'|'+ISNULL(A1.wap, 'NA')
+'|'+ISNULL(A1.book_val, 'NA')
+'|'+ISNULL(A1.market_val, 'NA')
+'|'+ISNULL(A1.mtm, 'NA')
+'|'+ISNULL(A1.yield, 'NA')
+'|'+ISNULL(A1.appreciation, 'NA')
+'|'+ISNULL(A1.depreciation, 'NA')
+'|'+ISNULL(A1.net_appreciation_depreciation, 'NA')
+'|'+ISNULL(A1.amort_as_on_dt, 'NA')
+'|'+ISNULL(A1.accounted_amort, 'NA')
+'|'+ISNULL(A1.un_accounted_amort, 'NA')
+'|'+ISNULL(A1.accrued_int, 'NA')
+'|'+ISNULL(A1.no_ca_skipped, 'NA')
+'|'+ISNULL(A1.ca_int_not_receieved, 'NA')
+'|'+ISNULL(A1.total_int, 'NA')
+'|'+ISNULL(A1.inst_id, 'NA')
+'|'+ISNULL(A1.inst_typ, 'NA')
+'|'+ISNULL(A1.isin_code, 'NA')
+'|'+ISNULL(A1.int_freq, 'NA')
+'|'+ISNULL(A1.int_practice, 'NA')
+'|'+ISNULL(A1.category, 'NA')
+'|'+ISNULL(A1.sub_category, 'NA')
+'|'+ISNULL(A1.put_dt, 'NA')
+'|'+ISNULL(A1.call_dt, 'NA')
+'|'+ISNULL(A1.lst_coupon, 'NA')
+'|'+ISNULL(A1.nxt_coupon, 'NA')
+'|'+ISNULL(A1.issue_dt, 'NA')
+'|'+ISNULL(A1.place, 'NA')
+'|'+ISNULL(A1.country, 'NA')
+'|'+ISNULL(A1.booking_basis, 'NA')
+'|'+ISNULL(A1.residual_maturity, 'NA')
+'|'+ISNULL(A1.slr_non_slr, 'NA')
+'|'+ISNULL(A1.listed, 'NA')
+'|'+ISNULL(A1.issuer_name, 'NA')
+'|'+ISNULL(A1.rating_agency, 'NA')
+'|'+ISNULL(A1.rating, 'NA')
+'|'+ISNULL(A1.market, 'NA')
+'|'+ISNULL(A1.asset_classification, 'NA')
+'|'+ISNULL(A1.gurantor, 'NA')
+'|'+ISNULL(A1.industry, 'NA')
+'|'+ISNULL(A1.sub_industry, 'NA')
+'|'+ISNULL(A1.borrower_category, 'NA')
+'|'+ISNULL(A1.asset_typ, 'NA')
+'|'+ISNULL(A1.asset_category, 'NA')
+'|'+ISNULL(A1.currency, 'NA')
+'|'+ISNULL(A1.coupon_classification_1, 'NA')
+'|'+ISNULL(A1.lst_rep_dt, 'NA')
+'|'+ISNULL(A1.nxt_rep_dt, 'NA')
+'|'+ISNULL(A1.m_duration, 'NA')
+'|'+ISNULL(A1.trsy_gl_cd, 'NA')
+'|'+ISNULL(C1.cf_type, 'Principal')
+'|'+ISNULL(C1.cf_amt,ISNULL(A1.book_val,0) )
+'|'+ISNULL(C1.cf_ccy,ISNULL(A1.currency,'INR'))
+'|'+ISNULL(C1.cf_dt,isnull(A1.maturity_dt,'01-01-2099')) as maturitydt
from SecDealData A1 left outer join SecDealCF C1
ON A1.inst_id=C1.inst_id
order by A1.inst_id