[package]
name = "mis-incr-vol-and-yield"
version = "1.0.3990"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
rbdate = { path = "../../libraries/RBDate" }
sdb_dyn_proto_rdr = { path = "../../libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../libraries/sdb_agg_rules" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
calamine = "0.18.0"
health_report = { path = "../../libraries/health_report" }
sdb_io = { path = "../../libraries/sdb_io" }
chrono = "0.4"
