[package]
name = "acctproc_int_rate"
version = "1.1.4297"
authors = ["Srinivas <srinivas.r@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
clap = "2.31.2"
calamine = "0.15.3"
csv = "1.1.1"
serde = "1.0.98"
serde_derive = "1.0.98"
health_report = { path = "../../../hdfc/libraries/health_report" }
chrono = "0.4.6"
protobuf = { version = "2.16.2", features = ["with-bytes"] }
