[package]
name = "additional_passthroughs"
version = "1.0.3510"
authors = ["Saurabh Singh <saurabh.s@surya-soft.com>"]

[dependencies]
rbdate = { path = "../../../../libraries/RBDate" }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
sdb_dyn_proto_rdr = { path = "../../../../libraries/sdb_dyn_proto_rdr" }
sdb_io = { path = "../../../../libraries/sdb_io" }
calamine = "0.19.1"
csv = "1.2.1"
chrono = "0.4.24"
