[package]
name = "tot_bal_gen"
version = "1.1.4849"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
health_report = { path = "../../../hdfc/libraries/health_report" }
protobuf = { version = "2.0", features = ["with-bytes"] }
calamine = "0.16.1"
