[package]
name = "llg_gl_recon_aggregator"
version = "1.0.3737"
edition = "2021"
authors = ["Ravindar Singh <ravindar.sr@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
slog-term = "2.9.0"
slog-async = "2.7.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
rbdate = { path = "../../../hdfc/libraries/RBDate" }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
sdb_agg_rules = { path = "../../libraries/sdb_agg_rules" }
health_report = { path = "../../../hdfc/libraries/health_report" }