[package]
name = "gl_threshold"
version = "1.0.1495"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
#sdb_agg_rules = { path = "../../libraries/sdb_agg_rules" }
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
health_report = { path = "../../libraries/health_report" }
slog-term = "2.4.0"
slog-async = "2.3.0"
calamine = "0.19.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
float-cmp = "0.4.0"
