[package]
name = "pp_undrawn_summry"
version = "1.1.5128"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
health_report = { path = "../../../libraries/health_report" }
clap = "2.31.2"
calamine = "0.15.3"
