[package]
name = "cf_ei_loans"
version = "1.0.5320"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
chrono = "0.4.31"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../hdfc/libraries/health_report" }
protobuf = { version = "2.0.0", features = ["with-bytes"] }
sdb_day_convention = { path = "../../../hdfc/libraries/sdb_day_convention"}
serde = "1.0.195"
serde_json = "1.0.111"
serde_derive = "1.0.195"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.8.0"
itertools="0.12.0"
