[package]
name = "cf_non_ei_loans"
version = "1.0.5261"
authors = ["srinivas644 <srinivas.r@surya-soft.com>"]

[dependencies]
clap = "2.32.0"
chrono = "0.4"
rbdate = { path = "../../../../SuperDB-Batch/hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../SuperDB-Batch/hdfc/libraries/sdb_io" }
health_report = { path = "../../../../SuperDB-Batch/hdfc/libraries/health_report" }
protobuf = { version = "2.15.0", features = ["with-bytes"] }
sdb_day_convention = { path = "../../../../SuperDB-Batch/hdfc/libraries/sdb_day_convention"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
