[package]
name = "restruct_pp"
version = "0.1.0"
authors = ["Shashank <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.33.1"
slog-term = "2.6.0"
slog-async = "2.5.0"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
calamine = "0.16.1"

