[package]
name = "td-liquidity"
version = "1.0.1"
authors = ["atush25 <atul.s@surya-soft.com>"]

[dependencies]

clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde ="1.0"
serde_json ="1.0"
serde_derive ="1.0"

rbdate = { path = "../../../../hdfc/libraries/RBDate/" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io/" }
health_report = { path = "../../../../hdfc/libraries/health_report/" }
