[package]
name = "cf_od"
version = "0.1.2996"
authors = ["Ravindar Singh <ravindar.sr@surya-soft.com>"]

[dependencies]
clap = "2.33.0"
chrono = "0.4"
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../../hdfc/libraries/health_report" }
protobuf = { version = "2.8.1", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.2"
slog-async = "2.3.0"
