[package]
name = "cf_lc_over"
version = "1.0.1"
authors = ["harishym <harish.m@surya-soft.com>"]

[dependencies]
calamine = "0.15.3"
clap = "2.32.0"
chrono = "0.4"
health_report = {path = "../../../libraries/health_report"}
protobuf = { version = "~2.0", features = ["with-bytes"] }
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
