[package]
name = "automated_proto"

version = "1.0.0"
authors = ["Pawan Jenu <pawan.j@surya-soft.com>"]

[dependencies]
clap = "2.33.3"
slog-term = "2.6.0"
slog-async = "2.5.0"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
serde_derive="1.0.115"
protoc-rust = "2.17.0"

