[package]
name = "pp_over_money_market_instruments"
version = "1.3.5458"
authors = ["Sougata Bhattacharjee <sougata.b@surya-soft.com>"]

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io" }
health_report = { path = "../../../libraries/health_report" }
clap = "2.31.2"
calamine = "0.18.0"
chrono = "0.4.6"
csv = "1.1.2"
serde = "1.0.98"
serde_derive = "1.0.98"
