[package]

name = "ubs_loan_loader"
version = "1.4.4734"
authors = ["sonali.s<sonali.s@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
health_report = { path = "../../../libraries/health_report" }
clap = "3.0.14"
calamine = "0.18.0"
chrono = "0.4"
serde = "1.0.104"
serde_derive = "1.0.104"
