[package]
name = "generate_metadata"
version = "1.1.1"
authors = ["Prajwal Dhatwalia <prajwal.dh@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io"}
sdb_util = { path = "../../libraries/sdb_util"}
serde_json = "1.0.41"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
serde_derive = "1.0.92"
