[package]
name = "ftp_acc_ie"
version = "1.0.3304"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.9.0"
slog-async = "2.7.0"
rbdate ={ path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../hdfc/libraries/health_report" }
clap = "3.1.18"
calamine = "0.18.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
