@echo off

@REM Command to create bcp.fmt file
BCP "SELECT STREAMDESC FROM RUNCONTROL_NAME.dbo.STREAMDEF where STREAMID=1004" QUERYOUT 1004.json  -S DB_CONNECTION_NAME -U RUNCONTROL_USERNAME -P RUNCONTROL_PASSWORD

