[package]
name = "daily_balance_program_casa"
version = "1.0.1"
authors = ["Saurabh Singh <saurabh.s@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
sdb_dyn_proto_rdr = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/sdb_agg_rules" }
rbdate = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/sdb_io" }
health_report = { path = "../../../../work_only/SuperDB-Batch/hdfc/libraries/health_report" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hashbrown = "0.12.3"
float-cmp = "0.4.0"
base64 = "0.13.0"
compressed_string = "1.0.0"
