#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub account_id: String,
    pub currency: String,
    pub int_rate: String,
    pub outstanding_bal: String,
    pub gl: String,
    pub start_date: String,
    pub maturity_date: String,
    pub customer_id: String,
    pub customer_type: String,
    pub lcy_amount: String,
    pub reference: String,
    pub npa_flag: String,
    pub npa_type: String,
    pub interest_type: String,
    pub int_repayment_frequency: String,
    pub last_repr_date: String,
    pub next_repr_date: String,
    pub cust_constitution_code: String,
    pub rate_flag: String,
    pub customer_name: String,
    pub product_code: String,
    pub account_type: String,
    pub branch: String,
    pub rm: String,
    pub group_code: String,
    pub monthly_avg_bal: String,
    pub aorl: String,
    pub rl1: String,
    pub rl2: String,
    pub rl3: String,
    pub customer_rating: String,
    pub p2: String,
    pub waiver_flag: String,
    pub accrued_int_amt: String,
    pub string1: String,
    pub string2: String,
    pub string3: String,
    pub number1: String,
    pub number2: String,
    pub number3: String,
    pub total_interest_amount: String,
    pub total_principal_amount: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            account_id: "account_id".to_string(),
            currency: "currency".to_string(),
            int_rate: "int_rate".to_string(),
            outstanding_bal: "outstanding_bal".to_string(),
            gl: "gl".to_string(),
            start_date: "start_date".to_string(),
            maturity_date: "maturity_date".to_string(),
            customer_id: "customer_id".to_string(),
            customer_type: "customer_type".to_string(),
            lcy_amount: "lcy_amount".to_string(),
            reference: "reference".to_string(),
            npa_flag: "npa_flag".to_string(),
            npa_type: "npa_type".to_string(),
            interest_type: "interest_type".to_string(),
            int_repayment_frequency: "int_repayment_frequency".to_string(),
            last_repr_date: "last_repr_date".to_string(),
            next_repr_date: "next_repr_date".to_string(),
            cust_constitution_code: "cust_constitution_code".to_string(),
            rate_flag: "rate_flag".to_string(),
            customer_name: "customer_name".to_string(),
            product_code: "product_code".to_string(),
            account_type: "acc_type".to_string(),
            branch: "branch".to_string(),
            rm: "rm".to_string(),
            group_code: "group_code".to_string(),
            monthly_avg_bal: "monthly_avg_bal".to_string(),
            aorl: "aorl".to_string(),
            rl1: "rl1".to_string(),
            rl2: "rl2".to_string(),
            rl3: "rl3".to_string(),
            customer_rating: "customer_rating".to_string(),
            p2: "p2".to_string(),
            waiver_flag: "waiver_flag".to_string(),
            accrued_int_amt: "accrued_int_amt".to_string(),
            string1: "string1".to_string(),
            string2: "string2".to_string(),
            string3: "string3".to_string(),
            number1: "number1".to_string(),
            number2: "number2".to_string(),
            number3: "number3".to_string(),
            total_interest_amount: "total_interest_amount".to_string(),
            total_principal_amount: "total_principal_amount".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
