[package]
name = "excel_append"
version = "0.1.2831"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]

[dependencies]
clap = "3.2.17"
slog-term = "2.9.0"
slog-async = "2.7.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
calamine = "0.18.0"
xlsxwriter = "0.4.0"

# This rbdate library path is relative so this might be needed to change as per config
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../hdfc/libraries/health_report" }
