#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub acc_id: String,
    pub cust_name: String,
    pub pout_bal: String,
    pub acc_int: String,
    pub st_dt: String,
    pub c_dt: String,
    pub gl_cd: String,
    pub int_rt: String,
    pub int_typ: String,
    pub int_bmark: String,
    pub rt_flag: String,
    pub prod_cd: String,
    pub nxt_pay_dt: String,
    pub mis1: String,
    pub mis2: String,
    pub ccy: String,
    pub ratings: String,
    pub rating_agency: String,
    pub asset_class: String,
    pub div: String,
    pub typ: String,
    pub originator: String,
    pub as_on_dt: String,
    pub rep_freq: String,
    pub nxt_rep_dt: String,
    pub alm_line: String,
    pub yeild: String,
    pub deal_name: String,
    pub total_interest_amount: String,
    pub total_principal_amount: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            acc_id: "acc_id".to_string(),
            cust_name: "cust_name".to_string(),
            pout_bal: "pout_bal".to_string(),
            acc_int: "acc_int".to_string(),
            st_dt: "st_dt".to_string(),
            c_dt: "c_dt".to_string(),
            gl_cd: "gl_cd".to_string(),
            int_rt: "int_rt".to_string(),
            int_typ: "int_typ".to_string(),
            int_bmark: "int_bmark".to_string(),
            rt_flag: "rt_flag".to_string(),
            prod_cd: "prod_cd".to_string(),
            nxt_pay_dt: "nxt_pay_dt".to_string(),
            mis1 : "mis1".to_string(),
            mis2: "mis2".to_string(),
            ccy: "ccy".to_string(),
            ratings: "ratings".to_string(),
            rating_agency: "rating_agency".to_string(),
            asset_class: "asset_class".to_string(),
            div: "div".to_string(),
            typ: "typ".to_string(),
            originator: "originator".to_string(),
            as_on_dt: "as_on_dt".to_string(),
            rep_freq: "rep_freq".to_string(),
            nxt_rep_dt: "nxt_rep_dt".to_string(),
            alm_line: "alm_line".to_string(),
            yeild: "yeild".to_string(),
            deal_name: "deal_name".to_string(),
            total_interest_amount: "total_interest_amount".to_string(),
            total_principal_amount: "total_principal_amount".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
