[package]
name = "cf-mabs-der"
version = "1.0.1"
authors = ["Harish Mudgal <harish.m@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.11"
time = "0.2.16"
protobuf = { version = "~2.0", features = ["with-bytes"] }
rbdate = { path = "../../../libraries/RBDate" }
calamine = "0.16.1"
sdb_io = { path = "../../../libraries/sdb_io" }
