[package]
name = "data_mask_fixed_len"
version = "1.0.2258"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]

[dependencies]
clap = "3.1.6"
sdb_dyn_proto_rdr = { path = "../../libraries/sdb_dyn_proto_rdr" }
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
health_report = { path = "../../libraries/health_report" }
slog-term = "2.9.0"
slog-async = "2.7.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.19"
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
float-cmp = "0.9.0"
