extern crate serde;
extern crate serde_derive;
use self::serde_derive::Deserialize;
use self::serde_derive::Serialize;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub rpt_dt: String,
    pub core_acc_typ_cd: String,
    pub core_acc_status_cd: String,
    pub int_period_cnt: String,
    pub overdraft_priviledges_flg: String,
    pub overdraft_flg: String,
    pub overdraft_limit_amt: String,
    pub acc_id: String,
    pub src_sys_cd: String,
    pub min_acc_open_amt: String,
    pub req_min_bal_amt: String,
    pub bureau_class_cd: String,
    pub late_payment_days_late_no: String,
    pub late_payment_status_cd: String,
    pub sector_cd: String,
    pub base_rate_cat: String,
    pub npa_provision: String,
    pub special_int_rt: String,
    pub rt_of_int: String,
    pub day_basis_cd: String,
    pub prd_cd: String,
    pub acc_typ: String,
    pub deposit_id: String,
    pub branch_code: String,
    pub cust_id: String,
    pub cust_typ: String,
    pub ccy_code: String,
    pub gl_code: String,
    pub out_bal: String,
    pub accrued_int_amt: String,
    pub int_from_dt: String,
    pub int_to_dt: String,
    pub open_dt: String,
    pub lst_cust_txn_dt: String,
    pub npa_dt: String,
    pub npa_flg: String,
    pub rating_code: String,
    pub ib_code: String,
    pub mclr_freq: String,
    pub mclr_int_strt_dt: String,
    pub ccy: String,
    pub prin_bal_amt: String,
    pub sub_amt_rec: String,
    pub subv_end_dt: String,
    pub sae_end_dt: String,
    pub lim_exp_dt: String,
    pub subsidy_apprn_dt: String,
    pub last_int_dr_dt: String,
    pub acct_suffix: String,
}
