[package]
name = "sdb_agg_rules_adj"
version = "0.2.0"
authors = ["Kavya <kavyashree.k@surya-soft.com>"]

[dependencies]
sdb_dyn_proto_rdr = { path = "../sdb_dyn_proto_rdr" }
sdb_io = { path = "../sdb_io" }
