[package]
name = "stmp_gl_bal"
version = "0.1.0"
authors = ["Prajwal Dhatwalia <prajwal.dh@surya-soft.com>"]

[dependencies]
chrono = "0.4"
clap="2.31.2"
protobuf = { version = "~2.0", features = ["with-bytes"] }
rbdate = { path = "../../../../hdfc/Libraries/RBDate" }
sdb_agg_rules = { path = "../../../../hdfc/Libraries/sdb_agg_rules" }
sdb_dyn_proto_rdr = { path = "../../../../hdfc/Libraries/sdb_dyn_proto_rdr" }
sdb_io ={path = "../../../../hdfc/Libraries/sdb_io" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
