use chrono::NaiveDate;

#[derive(Debug, Clone, PartialEq)]
pub struct OutputData {
    pub asondt: NaiveDate,
    pub llgid: String,
    pub country: String,
    pub ccy: String,
    pub bktschemeid: String,
    pub dim1itemid: String,
    pub dim2itemid: String,
    pub dim3itemid: String,
    pub dim4itemid: String,
    pub dim5itemid: String,
    pub b1amtccy: f64,
    pub b1amthcy: f64,
    pub b2amtccy: f64,
    pub b2amthcy: f64,
    pub b3amtccy: f64,
    pub b3amthcy: f64,
    pub b4amtccy: f64,
    pub b4amthcy: f64,
    pub b5amtccy: f64,
    pub b5amthcy: f64,
    pub b6amtccy: f64,
    pub b6amthcy: f64,
    pub b7amtccy: f64,
    pub b7amthcy: f64,
    pub b8amtccy: f64,
    pub b8amthcy: f64,
    pub b9amtccy: f64,
    pub b9amthcy: f64,
    pub b10amtccy: f64,
    pub b10amthcy: f64,
    pub b11amtccy: f64,
    pub b11amthcy: f64,
    pub b12amtccy: f64,
    pub b12amthcy: f64,
    pub b13amtccy: f64,
    pub b13amthcy: f64,
    pub b14amtccy: f64,
    pub b14amthcy: f64,
    pub b15amtccy: f64,
    pub b15amthcy: f64,
    pub b16amtccy: f64,
    pub b16amthcy: f64,
    pub b17amtccy: f64,
    pub b17amthcy: f64,
    pub b18amtccy: f64,
    pub b18amthcy: f64,
    pub b19amtccy: f64,
    pub b19amthcy: f64,
    pub b20amtccy: f64,
    pub b20amthcy: f64,
    pub b21amtccy: f64,
    pub b21amthcy: f64,
    pub b22amtccy: f64,
    pub b22amthcy: f64,
    pub b23amtccy: f64,
    pub b23amthcy: f64,
    pub b24amtccy: f64,
    pub b24amthcy: f64,
    pub b25amtccy: f64,
    pub b25amthcy: f64,
    pub b26amtccy: f64,
    pub b26amthcy: f64,
    pub b27amtccy: f64,
    pub b27amthcy: f64,
    pub b28amtccy: f64,
    pub b28amthcy: f64,
    pub b29amtccy: f64,
    pub b29amthcy: f64,
    pub b30amtccy: f64,
    pub b30amthcy: f64,
    pub totalamtccy: f64,
    pub totalamthcy: f64,
}
impl OutputData {
    pub fn new() -> Self {
        OutputData {
            asondt: NaiveDate::from_ymd_opt(1900, 1, 1).unwrap(),
            llgid: String::default(),
            country: String::default(),
            ccy: String::default(),
            bktschemeid: String::default(),
            dim1itemid: String::default(),
            dim2itemid: String::default(),
            dim3itemid: String::default(),
            dim4itemid: String::default(),
            dim5itemid: String::default(),
            b1amtccy: 0.0,
            b1amthcy: 0.0,
            b2amtccy: 0.0,
            b2amthcy: 0.0,
            b3amtccy: 0.0,
            b3amthcy: 0.0,
            b4amtccy: 0.0,
            b4amthcy: 0.0,
            b5amtccy: 0.0,
            b5amthcy: 0.0,
            b6amtccy: 0.0,
            b6amthcy: 0.0,
            b7amtccy: 0.0,
            b7amthcy: 0.0,
            b8amtccy: 0.0,
            b8amthcy: 0.0,
            b9amtccy: 0.0,
            b9amthcy: 0.0,
            b10amtccy: 0.0,
            b10amthcy: 0.0,
            b11amtccy: 0.0,
            b11amthcy: 0.0,
            b12amtccy: 0.0,
            b12amthcy: 0.0,
            b13amtccy: 0.0,
            b13amthcy: 0.0,
            b14amtccy: 0.0,
            b14amthcy: 0.0,
            b15amtccy: 0.0,
            b15amthcy: 0.0,
            b16amtccy: 0.0,
            b16amthcy: 0.0,
            b17amtccy: 0.0,
            b17amthcy: 0.0,
            b18amtccy: 0.0,
            b18amthcy: 0.0,
            b19amtccy: 0.0,
            b19amthcy: 0.0,
            b20amtccy: 0.0,
            b20amthcy: 0.0,
            b21amtccy: 0.0,
            b21amthcy: 0.0,
            b22amtccy: 0.0,
            b22amthcy: 0.0,
            b23amtccy: 0.0,
            b23amthcy: 0.0,
            b24amtccy: 0.0,
            b24amthcy: 0.0,
            b25amtccy: 0.0,
            b25amthcy: 0.0,
            b26amtccy: 0.0,
            b26amthcy: 0.0,
            b27amtccy: 0.0,
            b27amthcy: 0.0,
            b28amtccy: 0.0,
            b28amthcy: 0.0,
            b29amtccy: 0.0,
            b29amthcy: 0.0,
            b30amtccy: 0.0,
            b30amthcy: 0.0,
            totalamtccy: 0.0,
            totalamthcy: 0.0,
        }
    }
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}",
            self.asondt.format("%d-%m-%Y"),
            self.llgid,
            self.country,
            self.ccy,
            self.bktschemeid,
            self.dim1itemid,
            self.dim2itemid,
            self.dim3itemid,
            self.dim4itemid,
            self.dim5itemid,
            self.b1amtccy,
            self.b1amthcy,
            self.b2amtccy,
            self.b2amthcy,
            self.b3amtccy,
            self.b3amthcy,
            self.b4amtccy,
            self.b4amthcy,
            self.b5amtccy,
            self.b5amthcy,
            self.b6amtccy,
            self.b6amthcy,
            self.b7amtccy,
            self.b7amthcy,
            self.b8amtccy,
            self.b8amthcy,
            self.b9amtccy,
            self.b9amthcy,
            self.b10amtccy,
            self.b10amthcy,
            self.b11amtccy,
            self.b11amthcy,
            self.b12amtccy,
            self.b12amthcy,
            self.b13amtccy,
            self.b13amthcy,
            self.b14amtccy,
            self.b14amthcy,
            self.b15amtccy,
            self.b15amthcy,
            self.b16amtccy,
            self.b16amthcy,
            self.b17amtccy,
            self.b17amthcy,
            self.b18amtccy,
            self.b18amthcy,
            self.b19amtccy,
            self.b19amthcy,
            self.b20amtccy,
            self.b20amthcy,
            self.b21amtccy,
            self.b21amthcy,
            self.b22amtccy,
            self.b22amthcy,
            self.b23amtccy,
            self.b23amthcy,
            self.b24amtccy,
            self.b24amthcy,
            self.b25amtccy,
            self.b25amthcy,
            self.b26amtccy,
            self.b26amthcy,
            self.b27amtccy,
            self.b27amthcy,
            self.b28amtccy,
            self.b28amthcy,
            self.b29amtccy,
            self.b29amthcy,
            self.b30amtccy,
            self.b30amthcy,
            self.totalamtccy,
            self.totalamthcy,
        )
    }
}

#[derive(Debug, Clone)]
pub struct AmountStore {
    pub b1amtccy: f64,
    pub b1amthcy: f64,
    pub b2amtccy: f64,
    pub b2amthcy: f64,
    pub b3amtccy: f64,
    pub b3amthcy: f64,
    pub b4amtccy: f64,
    pub b4amthcy: f64,
}
