[package]
name = "sdb_dyn_proto_rdr"
version = "1.1.2186"
authors = ["mayurdhaka-suryasoftware <mayur.d@surya-soft.com>"]

[dependencies]
protoc-rust = "2.0"
protobuf = { version = "2.16.2", features = ["with-bytes"] }
sdb_io = { path = "../sdb_io" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"