[package]
name = "health_report"
version = "1.0.2884"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]

[dependencies]
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
