[package]
name = "incr_renewal_closed_accs"
version = "1.0.3816"
authors = ["NPunyashree <punyashree.n@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
protobuf = { version = "2.8.1", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
integer-encoding = "1.1.5"
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_dyn_proto_rdr = { path = "../../../hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
