[package]
name = "ind_blr05b_p1c"
version = "2.0.1"
authors = ["athulya <athulyababu.vk@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.2"
slog-async = "2.3.0"
rbdate = { path = "../../../../libraries/RBDate/" }
sdb_io = { path = "../../../../libraries/sdb_io/" }
clap = "2.33.0"
chrono = "0.4.10"
csv = "1.1.1"
serde = "1.0.104"
serde_derive = "1.0.104"
health_report = { path = "../../../../libraries/health_report/" }
calamine = "0.16.1"
