[package]
name = "benchmark-rates-extractor"
version = "1.1.0"
authors = ["Kavya <kavyashree.k@surya-soft.com>","Prajwal Dhatwalia <prajwal.dh@surya-soft.com>"]

[dependencies]
chrono = "0.4"
clap = "2.32.0"
protobuf = { version = "~2.0", features = ["with-bytes"] }
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io"}
sdb_util = { path = "../../../surya/libraries/sdb_util"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
