[package]
name = "mis_incr_td"
version = "0.1.0"
authors = ["shashank676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
sdb_dyn_proto_rdr = { path = "../../libraries/sdb_dyn_proto_rdr" }
rbdate = { path = "../../libraries/RBDate" }
sdb_io = { path = "../../libraries/sdb_io" }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"  # Remove this. Use all changes needed in the RBDate lib. Keeping it in for now for fast iteration.
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
health_report = { path = "../../libraries/health_report" }
