OPTIONS (SILENT=FEEDBACK)
LOAD DATA
INFILE '*' "STR '\n'"
APPEND
INTO TABLE "BASELLLGData" FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS 
(
"AsOnDt" DATE "DD-MM-YYYY",
"Country",
"CurrencyID",
"LLGID",
"NativAmt",
"ConsAmt"
)
