CREATE TABLE INP001_LOANS_FC
(
Branch varchar2(64),
CONTRACT_REF_NO varchar2(128),
USER_REF_NO varchar2(128),
Counterparty varchar2(256),
CUSTOMER_NAME1 varchar2(256),
Contract_Ccy  varchar2(5),
CCY_NUM number,
BOOKING_DATE DATE,
VALUE_DATE DATE,
MATURITY_DATE DATE,
PRODUCT_CODE varchar2(64),
PRODUCT_DESCRIPTION varchar2(256),
User_Defined_Status varchar2(24),
PAYMENT_METHOD Char(1),
Contract_Status Char(1),
CLOSURE_DATE DATE,
AMOUNT number(19,8),
LCY_AMOUNT number(19,8),
AC_CCY_OUTSTND_BAL number(19,8),
LCY_OUTSTND_BAL number(19,8),
GL varchar2(64),
description varchar2(256),
ACCRUAL_FREQUENCY char(1),
RATECODE varchar2(64),
RATETYPE char(1),
Ratespread number(19,8),
INT_RATE number(19,8),
PENAL_RATE number(19,8),
LAST_RESET_DATE DATE,
NEXT_RESET_DATE DATE,
COMP_MIS_1 number,
COMP_MIS_2 number,
COMP_MIS_3 number,
Txn_Mis_2 number,
DUE_DT_PRINCIPAL DATE,
Due_Dt_Interest DATE,
FREQUENCY varchar2(16),
Principal_start_DATE DATE,
interest_start_date DATE,
INTCALCMETH number,
BENCHMARK_RATE varchar2(64),
RISKBASEPRICING varchar2(64)
);

