OPTIONS (SKIP=1)
LOAD DATA
INFILE '/data/HDFC/input/alm_loan_schedule_20190408_013020057.csv' "STR '\r\n'"
TRUNCATE
INTO TABLE INP003_FC_LOANS04 FIELDS TERMINATED BY '~'
 TRAILING NULLCOLS 
(
REFERENCE,
COMPONENT,
SCHEDULE_DUE_DATE DATE "DD-mm-YYYY",
AMOUNT_DUE,
AMOUNT_SETTLED
)
