[package]
name = "cf_dep_over"
version = "1.2.2604"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
chrono = "0.4"
rbconcurrency = { path = "../../../../libraries/RBConcurrency" }
rbdate = { path = "../../../../libraries/RBDate" }
sdb_day_convention = { path = "../../../../libraries/sdb_day_convention" }
sdb_io = { path = "../../../../libraries/sdb_io" }
health_report = { path = "../../../../libraries/health_report" }
protobuf = { version = "2.25.1", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
