[package]
name = "rules-extractor"
version = "0.1.0"
authors = ["shashank.676 <shashank.p@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4.18"
dbpool = { path = "../../libraries/dbpool" }
r2d2 = { path = "../../libraries/r2d2" }
oracle = { version = "0.2.1", features = ["chrono"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"