[package]
name = "ftp_stmp_mat"
version = "1.3.3691"
authors = ["kavya","Prajwal Dhatwalia <prajwal.dh@surya-soft.com>"]

[dependencies]
clap="2.31.2"
health_report = { path = "../../../../hdfc/libraries/health_report" }
sdb_dyn_proto_rdr = { path = "../../../../hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../../surya/libraries/sdb_agg_rules" }
sdb_agg_rules_adj = { path = "../../../../hdfc/libraries/sdb_agg_rules_adj" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
sdb_util = { path = "../../../../surya/libraries/sdb_util" }
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
chrono = "0.4"
rbconcurrency = { path = "../../../../hdfc/libraries/RBConcurrency" }
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
protobuf = { version = "2.16.2", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
