[package]
name = "cf_td_merger"
version = "1.0.4030"
authors = ["srinivas644 <srinivas.r@surya-soft.com>"]

[dependencies]
clap = "2.32.0"
sdb_dyn_proto_rdr = { path = "../../../../hdfc/libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../../surya/libraries/sdb_agg_rules" }
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io" }
health_report = { path = "../../../../hdfc/libraries/health_report" }
additional_passthroughs= {path = "../libraries/additional-passthroughs"}
protobuf = { version = "2.15.0", features = ["with-bytes"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
float-cmp = "0.4.0"
calamine = "0.21.2"
