[package]
name = "cf_borr_and_lend"
version = "0.1.0"
authors = ["BSParis <paris.bs@surya-soft.com>"]

[dependencies]
clap = "2.32.0"
sdb_io = {path = "../../../../hdfc/libraries/sdb_io"}
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
rbconcurrency = { path = "../../../../hdfc/libraries/RBConcurrency" }
health_report = { path = "../../../../hdfc/libraries/health_report" }
sdb_day_convention = { path = "../../../../hdfc/libraries/sdb_day_convention"}
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
protobuf = { version = "~2.0", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
