#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub deal_id: String,
    pub branch: String,
    pub instrument_name: String,
    pub lending_borrowing_type: String,
    pub typology: String,
    pub usage: String,
    pub sub_type_borrowing_lending: String,
    pub counterparty: String,
    pub creation_date: String,
    pub val_date: String,
    pub deal_date: String,
    pub currency: String,
    pub current_deal_amount: String,
    pub current_conversion_rate_lcy: String,
    pub current_deal_amount_lcy: String,
    pub roi: String,
    pub tenor_days: String,
    pub maturity_dt: String,
    pub principal_amount: String,
    pub interest_amount: String,
    pub cf_type: String,
    pub flow_type: String,
    pub maturity_amount: String,
    pub dealer_name: String,
    pub ndsreferenceno: String,
    pub next_fixing_date: String,
    pub residual_tenor: String,
    pub next_put_date: String,
    pub next_call_date: String,
    pub next_interest_payout_date: String,
    pub interest_payout_tenor: String,
    pub aip_air: String,
    pub downgrade_clause: String,
    pub average_monthly_balance: String,
    pub glcode: String,
    pub counterparty_category_1: String,
    pub counterparty_category_2: String,
    pub counterparty_category_3: String,
    pub counterparty_category_4: String,
    pub interest_payable_receivable_till_the_next_payout_date: String,
    pub bucket_days: String,
    pub system_gl: String,
    pub alm_concat: String,
    pub division: String,
    pub alm_line: String,
    pub ia_line: String,
    pub total_interest_amount: String,
    pub total_principal_amount: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            deal_id: "deal_id".to_string(),
            branch: "branch".to_string(),
            instrument_name: "instrument_name".to_string(),
            lending_borrowing_type: "lending_borrowing_type".to_string(),
            typology: "typology".to_string(),
            usage: "usage".to_string(),
            sub_type_borrowing_lending: "sub_type_borrowing_lending".to_string(),
            counterparty: "counterparty".to_string(),
            creation_date: "creation_date".to_string(),
            val_date: "val_date".to_string(),
            deal_date: "deal_date".to_string(),
            currency: "currency".to_string(),
            current_deal_amount: "current_deal_amount".to_string(),
            current_conversion_rate_lcy: "current_conversion_rate_lcy".to_string(),
            current_deal_amount_lcy: "current_deal_amount_lcy".to_string(),
            roi: "roi".to_string(),
            tenor_days: "tenor_days".to_string(),
            maturity_dt: "maturity_dt".to_string(),
            principal_amount: "principal_amount".to_string(),
            interest_amount: "interest_amount".to_string(),
            cf_type: "cf_type".to_string(),
            flow_type: "flow_type".to_string(),
            maturity_amount: "maturity_amount".to_string(),
            dealer_name: "dealer_name".to_string(),
            ndsreferenceno: "ndsreferenceno".to_string(),
            next_fixing_date: "next_fixing_date".to_string(),
            residual_tenor: "residual_tenor".to_string(),
            next_put_date: "next_put_date".to_string(),
            next_call_date: "next_call_date".to_string(),
            next_interest_payout_date: "next_interest_payout_date".to_string(),
            interest_payout_tenor: "interest_payout_tenor".to_string(),
            aip_air: "aip_air".to_string(),
            downgrade_clause: "downgrade_clause".to_string(),
            average_monthly_balance: "average_monthly_balance".to_string(),
            glcode: "glcode".to_string(),
            counterparty_category_1: "counterparty_category_1".to_string(),
            counterparty_category_2: "counterparty_category_2".to_string(),
            counterparty_category_3: "counterparty_category_3".to_string(),
            counterparty_category_4: "counterparty_category_4".to_string(),
            interest_payable_receivable_till_the_next_payout_date:
                "interest_payable_receivable_till_the_next_payout_date".to_string(),
            bucket_days: "bucket_days".to_string(),
            system_gl: "system_gl".to_string(),
            alm_concat: "alm_concat".to_string(),
            division: "division".to_string(),
            alm_line: "alm_line".to_string(),
            ia_line: "ia_line".to_string(),
            total_interest_amount: "total_interest_amount".to_string(),
            total_principal_amount: "total_principal_amount".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
