[package]
name = "subsidiary_lcr"
version = "1.2.5206"
authors = ["harishym <harish.m@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
serde_derive = "1.0.106"
rbdate = { path = "../../../../SuperDB-Batch/hdfc/libraries/RBDate" }
csv = "1.1.3"
calamine = "0.16.1"
