#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub reference: String,
    pub cust: String,
    pub curr: String,
    pub val_dt: String,
    pub mat_dt: String,
    pub npa_stats: String,
    pub gl: String,
    pub int_rt: String,
    pub cust_name: String,
    pub comp_mis1: String,
    pub comp_mis2: String,
    pub loan_type: String,
    pub acurl_basis: String,
    pub div: String,
    pub alm_line: String,
    pub ia_llg: String,
    pub balm_llg: String,
    pub as_on_dt: String,
    pub nxt_rep_dt: String,
    pub exchange_rt: String,
    pub asset_class: String,
    pub tot_int_amt: String,
    pub tot_prin_amt: String,
    pub int_st_dt: String,
    pub bal_os_amt_lcy: String,
    pub bill_amt: String,
    pub concat: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            reference: "reference".to_string(),
            cust: "cust".to_string(),
            curr: "curr".to_string(),
            val_dt: "val_dt".to_string(),
            mat_dt: "mat_dt".to_string(),
            npa_stats: "npa_stats".to_string(),
            gl: "gl".to_string(),
            int_rt: "int_rt".to_string(),
            cust_name: "cust_name".to_string(),
            comp_mis1: "comp_mis1".to_string(),
            comp_mis2: "comp_mis2".to_string(),
            loan_type: "loan_type".to_string(),
            acurl_basis: "acurl_basis".to_string(),
            div: "div".to_string(),
            alm_line: "alm_line".to_string(),
            ia_llg: "ia_llg".to_string(),
            balm_llg: "balm_llg".to_string(),
            as_on_dt: "as_on_dt".to_string(),
            nxt_rep_dt: "nxt_rep_dt".to_string(),
            exchange_rt: "exchange_rt".to_string(),
            asset_class: "asset_class".to_string(),
            tot_int_amt: "tot_int_amt".to_string(),
            tot_prin_amt: "tot_prin_amt".to_string(),
            int_st_dt: "int_st_dt".to_string(),
            bal_os_amt_lcy: "bal_os_amt_lcy".to_string(),
            bill_amt: "bill_amt".to_string(),
            concat: "concat".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
