
[package]
name ="remote_to_live"
version = "0.1.0"
authors = ["Pawan Jenu <pawan.j@surya-soft.com>"]

[dependencies]
clap = "2.31.2"
slog-term = "2.4.0"
slog-async = "2.3.0"

openssl-sys = "0.9"
openssl = "0.10"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_derive="1.0.117"
fs_extra = "1.2.0"
walkdir = "2.3.1"
ssh2 = { path = "../extern_crates/ssh2-rs-master" }
chrono = "0.4.19"
indicatif = "0.15"
lazy_static = "1.4.0"
colored = "2"
filetime = "0.2.12"
term_size = "0.3.2"
termion = "1.5.5"
crossterm_cursor = "0.4.0"
terminal-menu = "*"
rprompt = "*"
