// This file is generated by rust-protobuf 2.4.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct Cashflow {
    // message fields
    pub int_amt: f64,
    pub prin_amt: f64,
    pub date: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl Cashflow {
    pub fn new() -> Cashflow {
        ::std::default::Default::default()
    }

    // double int_amt = 1;

    pub fn clear_int_amt(&mut self) {
        self.int_amt = 0.;
    }

    // Param is passed by value, moved
    pub fn set_int_amt(&mut self, v: f64) {
        self.int_amt = v;
    }

    pub fn get_int_amt(&self) -> f64 {
        self.int_amt
    }

    // double prin_amt = 2;

    pub fn clear_prin_amt(&mut self) {
        self.prin_amt = 0.;
    }

    // Param is passed by value, moved
    pub fn set_prin_amt(&mut self, v: f64) {
        self.prin_amt = v;
    }

    pub fn get_prin_amt(&self) -> f64 {
        self.prin_amt
    }

    // int64 date = 3;

    pub fn clear_date(&mut self) {
        self.date = 0;
    }

    // Param is passed by value, moved
    pub fn set_date(&mut self, v: i64) {
        self.date = v;
    }

    pub fn get_date(&self) -> i64 {
        self.date
    }
}

impl ::protobuf::Message for Cashflow {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.int_amt = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.prin_amt = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.date = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.int_amt != 0. {
            my_size += 9;
        }
        if self.prin_amt != 0. {
            my_size += 9;
        }
        if self.date != 0 {
            my_size += ::protobuf::rt::value_size(3, self.date, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.int_amt != 0. {
            os.write_double(1, self.int_amt)?;
        }
        if self.prin_amt != 0. {
            os.write_double(2, self.prin_amt)?;
        }
        if self.date != 0 {
            os.write_int64(3, self.date)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Cashflow {
        Cashflow::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "int_amt",
                    |m: &Cashflow| { &m.int_amt },
                    |m: &mut Cashflow| { &mut m.int_amt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "prin_amt",
                    |m: &Cashflow| { &m.prin_amt },
                    |m: &mut Cashflow| { &mut m.prin_amt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "date",
                    |m: &Cashflow| { &m.date },
                    |m: &mut Cashflow| { &mut m.date },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<Cashflow>(
                    "Cashflow",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Cashflow {
        static mut instance: ::protobuf::lazy::Lazy<Cashflow> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const Cashflow,
        };
        unsafe {
            instance.get(Cashflow::new)
        }
    }
}

impl ::protobuf::Clear for Cashflow {
    fn clear(&mut self) {
        self.clear_int_amt();
        self.clear_prin_amt();
        self.clear_date();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Cashflow {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Cashflow {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct AccountWithCashflows {
    // message fields
    pub account_id: ::std::string::String,
    pub currency: ::std::string::String,
    pub int_rate: f64,
    pub outstanding_bal: f64,
    pub gl: i64,
    pub start_date: i64,
    pub maturity_date: i64,
    pub customer_id: ::std::string::String,
    pub customer_type: ::std::string::String,
    pub lcy_amount: f64,
    pub reference: ::std::string::String,
    pub npa_flag: ::std::string::String,
    pub npa_type: ::std::string::String,
    pub interest_type: ::std::string::String,
    pub int_repayment_frequency: i64,
    pub last_repr_date: i64,
    pub next_repr_date: i64,
    pub cust_constitution_code: i64,
    pub rate_flag: ::std::string::String,
    pub customer_name: ::std::string::String,
    pub product_code: ::std::string::String,
    pub account_type: ::std::string::String,
    pub branch: ::std::string::String,
    pub rm: ::std::string::String,
    pub group_code: ::std::string::String,
    pub monthly_avg_bal: ::std::string::String,
    pub aorl: ::std::string::String,
    pub rl1: i32,
    pub rl2: i32,
    pub rl3: i32,
    pub customer_rating: ::std::string::String,
    pub p2: ::std::string::String,
    pub waiver_flag: ::std::string::String,
    pub accrued_int_amt: ::std::string::String,
    pub string1: ::std::string::String,
    pub string2: ::std::string::String,
    pub string3: ::std::string::String,
    pub number1: i64,
    pub number2: i64,
    pub number3: i64,
    pub total_interest_amount: f64,
    pub total_principal_amount: f64,
    pub cashflows: ::protobuf::RepeatedField<Cashflow>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl AccountWithCashflows {
    pub fn new() -> AccountWithCashflows {
        ::std::default::Default::default()
    }

    // string account_id = 1;

    pub fn clear_account_id(&mut self) {
        self.account_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_account_id(&mut self, v: ::std::string::String) {
        self.account_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_account_id(&mut self) -> &mut ::std::string::String {
        &mut self.account_id
    }

    // Take field
    pub fn take_account_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.account_id, ::std::string::String::new())
    }

    pub fn get_account_id(&self) -> &str {
        &self.account_id
    }

    // string currency = 2;

    pub fn clear_currency(&mut self) {
        self.currency.clear();
    }

    // Param is passed by value, moved
    pub fn set_currency(&mut self, v: ::std::string::String) {
        self.currency = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_currency(&mut self) -> &mut ::std::string::String {
        &mut self.currency
    }

    // Take field
    pub fn take_currency(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.currency, ::std::string::String::new())
    }

    pub fn get_currency(&self) -> &str {
        &self.currency
    }

    // double int_rate = 3;

    pub fn clear_int_rate(&mut self) {
        self.int_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_int_rate(&mut self, v: f64) {
        self.int_rate = v;
    }

    pub fn get_int_rate(&self) -> f64 {
        self.int_rate
    }

    // double outstanding_bal = 4;

    pub fn clear_outstanding_bal(&mut self) {
        self.outstanding_bal = 0.;
    }

    // Param is passed by value, moved
    pub fn set_outstanding_bal(&mut self, v: f64) {
        self.outstanding_bal = v;
    }

    pub fn get_outstanding_bal(&self) -> f64 {
        self.outstanding_bal
    }

    // int64 gl = 5;

    pub fn clear_gl(&mut self) {
        self.gl = 0;
    }

    // Param is passed by value, moved
    pub fn set_gl(&mut self, v: i64) {
        self.gl = v;
    }

    pub fn get_gl(&self) -> i64 {
        self.gl
    }

    // int64 start_date = 6;

    pub fn clear_start_date(&mut self) {
        self.start_date = 0;
    }

    // Param is passed by value, moved
    pub fn set_start_date(&mut self, v: i64) {
        self.start_date = v;
    }

    pub fn get_start_date(&self) -> i64 {
        self.start_date
    }

    // int64 maturity_date = 7;

    pub fn clear_maturity_date(&mut self) {
        self.maturity_date = 0;
    }

    // Param is passed by value, moved
    pub fn set_maturity_date(&mut self, v: i64) {
        self.maturity_date = v;
    }

    pub fn get_maturity_date(&self) -> i64 {
        self.maturity_date
    }

    // string customer_id = 8;

    pub fn clear_customer_id(&mut self) {
        self.customer_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_customer_id(&mut self, v: ::std::string::String) {
        self.customer_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_customer_id(&mut self) -> &mut ::std::string::String {
        &mut self.customer_id
    }

    // Take field
    pub fn take_customer_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.customer_id, ::std::string::String::new())
    }

    pub fn get_customer_id(&self) -> &str {
        &self.customer_id
    }

    // string customer_type = 9;

    pub fn clear_customer_type(&mut self) {
        self.customer_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_customer_type(&mut self, v: ::std::string::String) {
        self.customer_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_customer_type(&mut self) -> &mut ::std::string::String {
        &mut self.customer_type
    }

    // Take field
    pub fn take_customer_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.customer_type, ::std::string::String::new())
    }

    pub fn get_customer_type(&self) -> &str {
        &self.customer_type
    }

    // double lcy_amount = 10;

    pub fn clear_lcy_amount(&mut self) {
        self.lcy_amount = 0.;
    }

    // Param is passed by value, moved
    pub fn set_lcy_amount(&mut self, v: f64) {
        self.lcy_amount = v;
    }

    pub fn get_lcy_amount(&self) -> f64 {
        self.lcy_amount
    }

    // string reference = 11;

    pub fn clear_reference(&mut self) {
        self.reference.clear();
    }

    // Param is passed by value, moved
    pub fn set_reference(&mut self, v: ::std::string::String) {
        self.reference = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_reference(&mut self) -> &mut ::std::string::String {
        &mut self.reference
    }

    // Take field
    pub fn take_reference(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.reference, ::std::string::String::new())
    }

    pub fn get_reference(&self) -> &str {
        &self.reference
    }

    // string npa_flag = 12;

    pub fn clear_npa_flag(&mut self) {
        self.npa_flag.clear();
    }

    // Param is passed by value, moved
    pub fn set_npa_flag(&mut self, v: ::std::string::String) {
        self.npa_flag = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_npa_flag(&mut self) -> &mut ::std::string::String {
        &mut self.npa_flag
    }

    // Take field
    pub fn take_npa_flag(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.npa_flag, ::std::string::String::new())
    }

    pub fn get_npa_flag(&self) -> &str {
        &self.npa_flag
    }

    // string npa_type = 13;

    pub fn clear_npa_type(&mut self) {
        self.npa_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_npa_type(&mut self, v: ::std::string::String) {
        self.npa_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_npa_type(&mut self) -> &mut ::std::string::String {
        &mut self.npa_type
    }

    // Take field
    pub fn take_npa_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.npa_type, ::std::string::String::new())
    }

    pub fn get_npa_type(&self) -> &str {
        &self.npa_type
    }

    // string interest_type = 14;

    pub fn clear_interest_type(&mut self) {
        self.interest_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_interest_type(&mut self, v: ::std::string::String) {
        self.interest_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_interest_type(&mut self) -> &mut ::std::string::String {
        &mut self.interest_type
    }

    // Take field
    pub fn take_interest_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.interest_type, ::std::string::String::new())
    }

    pub fn get_interest_type(&self) -> &str {
        &self.interest_type
    }

    // int64 int_repayment_frequency = 15;

    pub fn clear_int_repayment_frequency(&mut self) {
        self.int_repayment_frequency = 0;
    }

    // Param is passed by value, moved
    pub fn set_int_repayment_frequency(&mut self, v: i64) {
        self.int_repayment_frequency = v;
    }

    pub fn get_int_repayment_frequency(&self) -> i64 {
        self.int_repayment_frequency
    }

    // int64 last_repr_date = 16;

    pub fn clear_last_repr_date(&mut self) {
        self.last_repr_date = 0;
    }

    // Param is passed by value, moved
    pub fn set_last_repr_date(&mut self, v: i64) {
        self.last_repr_date = v;
    }

    pub fn get_last_repr_date(&self) -> i64 {
        self.last_repr_date
    }

    // int64 next_repr_date = 17;

    pub fn clear_next_repr_date(&mut self) {
        self.next_repr_date = 0;
    }

    // Param is passed by value, moved
    pub fn set_next_repr_date(&mut self, v: i64) {
        self.next_repr_date = v;
    }

    pub fn get_next_repr_date(&self) -> i64 {
        self.next_repr_date
    }

    // int64 cust_constitution_code = 18;

    pub fn clear_cust_constitution_code(&mut self) {
        self.cust_constitution_code = 0;
    }

    // Param is passed by value, moved
    pub fn set_cust_constitution_code(&mut self, v: i64) {
        self.cust_constitution_code = v;
    }

    pub fn get_cust_constitution_code(&self) -> i64 {
        self.cust_constitution_code
    }

    // string rate_flag = 19;

    pub fn clear_rate_flag(&mut self) {
        self.rate_flag.clear();
    }

    // Param is passed by value, moved
    pub fn set_rate_flag(&mut self, v: ::std::string::String) {
        self.rate_flag = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rate_flag(&mut self) -> &mut ::std::string::String {
        &mut self.rate_flag
    }

    // Take field
    pub fn take_rate_flag(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rate_flag, ::std::string::String::new())
    }

    pub fn get_rate_flag(&self) -> &str {
        &self.rate_flag
    }

    // string customer_name = 20;

    pub fn clear_customer_name(&mut self) {
        self.customer_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_customer_name(&mut self, v: ::std::string::String) {
        self.customer_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_customer_name(&mut self) -> &mut ::std::string::String {
        &mut self.customer_name
    }

    // Take field
    pub fn take_customer_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.customer_name, ::std::string::String::new())
    }

    pub fn get_customer_name(&self) -> &str {
        &self.customer_name
    }

    // string product_code = 21;

    pub fn clear_product_code(&mut self) {
        self.product_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_product_code(&mut self, v: ::std::string::String) {
        self.product_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_product_code(&mut self) -> &mut ::std::string::String {
        &mut self.product_code
    }

    // Take field
    pub fn take_product_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.product_code, ::std::string::String::new())
    }

    pub fn get_product_code(&self) -> &str {
        &self.product_code
    }

    // string account_type = 22;

    pub fn clear_account_type(&mut self) {
        self.account_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_account_type(&mut self, v: ::std::string::String) {
        self.account_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_account_type(&mut self) -> &mut ::std::string::String {
        &mut self.account_type
    }

    // Take field
    pub fn take_account_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.account_type, ::std::string::String::new())
    }

    pub fn get_account_type(&self) -> &str {
        &self.account_type
    }

    // string branch = 23;

    pub fn clear_branch(&mut self) {
        self.branch.clear();
    }

    // Param is passed by value, moved
    pub fn set_branch(&mut self, v: ::std::string::String) {
        self.branch = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_branch(&mut self) -> &mut ::std::string::String {
        &mut self.branch
    }

    // Take field
    pub fn take_branch(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.branch, ::std::string::String::new())
    }

    pub fn get_branch(&self) -> &str {
        &self.branch
    }

    // string rm = 24;

    pub fn clear_rm(&mut self) {
        self.rm.clear();
    }

    // Param is passed by value, moved
    pub fn set_rm(&mut self, v: ::std::string::String) {
        self.rm = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_rm(&mut self) -> &mut ::std::string::String {
        &mut self.rm
    }

    // Take field
    pub fn take_rm(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.rm, ::std::string::String::new())
    }

    pub fn get_rm(&self) -> &str {
        &self.rm
    }

    // string group_code = 25;

    pub fn clear_group_code(&mut self) {
        self.group_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_group_code(&mut self, v: ::std::string::String) {
        self.group_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_group_code(&mut self) -> &mut ::std::string::String {
        &mut self.group_code
    }

    // Take field
    pub fn take_group_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.group_code, ::std::string::String::new())
    }

    pub fn get_group_code(&self) -> &str {
        &self.group_code
    }

    // string monthly_avg_bal = 26;

    pub fn clear_monthly_avg_bal(&mut self) {
        self.monthly_avg_bal.clear();
    }

    // Param is passed by value, moved
    pub fn set_monthly_avg_bal(&mut self, v: ::std::string::String) {
        self.monthly_avg_bal = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_monthly_avg_bal(&mut self) -> &mut ::std::string::String {
        &mut self.monthly_avg_bal
    }

    // Take field
    pub fn take_monthly_avg_bal(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.monthly_avg_bal, ::std::string::String::new())
    }

    pub fn get_monthly_avg_bal(&self) -> &str {
        &self.monthly_avg_bal
    }

    // string aorl = 27;

    pub fn clear_aorl(&mut self) {
        self.aorl.clear();
    }

    // Param is passed by value, moved
    pub fn set_aorl(&mut self, v: ::std::string::String) {
        self.aorl = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_aorl(&mut self) -> &mut ::std::string::String {
        &mut self.aorl
    }

    // Take field
    pub fn take_aorl(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.aorl, ::std::string::String::new())
    }

    pub fn get_aorl(&self) -> &str {
        &self.aorl
    }

    // int32 rl1 = 28;

    pub fn clear_rl1(&mut self) {
        self.rl1 = 0;
    }

    // Param is passed by value, moved
    pub fn set_rl1(&mut self, v: i32) {
        self.rl1 = v;
    }

    pub fn get_rl1(&self) -> i32 {
        self.rl1
    }

    // int32 rl2 = 29;

    pub fn clear_rl2(&mut self) {
        self.rl2 = 0;
    }

    // Param is passed by value, moved
    pub fn set_rl2(&mut self, v: i32) {
        self.rl2 = v;
    }

    pub fn get_rl2(&self) -> i32 {
        self.rl2
    }

    // int32 rl3 = 30;

    pub fn clear_rl3(&mut self) {
        self.rl3 = 0;
    }

    // Param is passed by value, moved
    pub fn set_rl3(&mut self, v: i32) {
        self.rl3 = v;
    }

    pub fn get_rl3(&self) -> i32 {
        self.rl3
    }

    // string customer_rating = 31;

    pub fn clear_customer_rating(&mut self) {
        self.customer_rating.clear();
    }

    // Param is passed by value, moved
    pub fn set_customer_rating(&mut self, v: ::std::string::String) {
        self.customer_rating = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_customer_rating(&mut self) -> &mut ::std::string::String {
        &mut self.customer_rating
    }

    // Take field
    pub fn take_customer_rating(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.customer_rating, ::std::string::String::new())
    }

    pub fn get_customer_rating(&self) -> &str {
        &self.customer_rating
    }

    // string p2 = 32;

    pub fn clear_p2(&mut self) {
        self.p2.clear();
    }

    // Param is passed by value, moved
    pub fn set_p2(&mut self, v: ::std::string::String) {
        self.p2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_p2(&mut self) -> &mut ::std::string::String {
        &mut self.p2
    }

    // Take field
    pub fn take_p2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.p2, ::std::string::String::new())
    }

    pub fn get_p2(&self) -> &str {
        &self.p2
    }

    // string waiver_flag = 33;

    pub fn clear_waiver_flag(&mut self) {
        self.waiver_flag.clear();
    }

    // Param is passed by value, moved
    pub fn set_waiver_flag(&mut self, v: ::std::string::String) {
        self.waiver_flag = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_waiver_flag(&mut self) -> &mut ::std::string::String {
        &mut self.waiver_flag
    }

    // Take field
    pub fn take_waiver_flag(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.waiver_flag, ::std::string::String::new())
    }

    pub fn get_waiver_flag(&self) -> &str {
        &self.waiver_flag
    }

    // string accrued_int_amt = 34;

    pub fn clear_accrued_int_amt(&mut self) {
        self.accrued_int_amt.clear();
    }

    // Param is passed by value, moved
    pub fn set_accrued_int_amt(&mut self, v: ::std::string::String) {
        self.accrued_int_amt = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_accrued_int_amt(&mut self) -> &mut ::std::string::String {
        &mut self.accrued_int_amt
    }

    // Take field
    pub fn take_accrued_int_amt(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.accrued_int_amt, ::std::string::String::new())
    }

    pub fn get_accrued_int_amt(&self) -> &str {
        &self.accrued_int_amt
    }

    // string string1 = 35;

    pub fn clear_string1(&mut self) {
        self.string1.clear();
    }

    // Param is passed by value, moved
    pub fn set_string1(&mut self, v: ::std::string::String) {
        self.string1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_string1(&mut self) -> &mut ::std::string::String {
        &mut self.string1
    }

    // Take field
    pub fn take_string1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.string1, ::std::string::String::new())
    }

    pub fn get_string1(&self) -> &str {
        &self.string1
    }

    // string string2 = 36;

    pub fn clear_string2(&mut self) {
        self.string2.clear();
    }

    // Param is passed by value, moved
    pub fn set_string2(&mut self, v: ::std::string::String) {
        self.string2 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_string2(&mut self) -> &mut ::std::string::String {
        &mut self.string2
    }

    // Take field
    pub fn take_string2(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.string2, ::std::string::String::new())
    }

    pub fn get_string2(&self) -> &str {
        &self.string2
    }

    // string string3 = 37;

    pub fn clear_string3(&mut self) {
        self.string3.clear();
    }

    // Param is passed by value, moved
    pub fn set_string3(&mut self, v: ::std::string::String) {
        self.string3 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_string3(&mut self) -> &mut ::std::string::String {
        &mut self.string3
    }

    // Take field
    pub fn take_string3(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.string3, ::std::string::String::new())
    }

    pub fn get_string3(&self) -> &str {
        &self.string3
    }

    // int64 number1 = 38;

    pub fn clear_number1(&mut self) {
        self.number1 = 0;
    }

    // Param is passed by value, moved
    pub fn set_number1(&mut self, v: i64) {
        self.number1 = v;
    }

    pub fn get_number1(&self) -> i64 {
        self.number1
    }

    // int64 number2 = 39;

    pub fn clear_number2(&mut self) {
        self.number2 = 0;
    }

    // Param is passed by value, moved
    pub fn set_number2(&mut self, v: i64) {
        self.number2 = v;
    }

    pub fn get_number2(&self) -> i64 {
        self.number2
    }

    // int64 number3 = 40;

    pub fn clear_number3(&mut self) {
        self.number3 = 0;
    }

    // Param is passed by value, moved
    pub fn set_number3(&mut self, v: i64) {
        self.number3 = v;
    }

    pub fn get_number3(&self) -> i64 {
        self.number3
    }

    // double total_interest_amount = 41;

    pub fn clear_total_interest_amount(&mut self) {
        self.total_interest_amount = 0.;
    }

    // Param is passed by value, moved
    pub fn set_total_interest_amount(&mut self, v: f64) {
        self.total_interest_amount = v;
    }

    pub fn get_total_interest_amount(&self) -> f64 {
        self.total_interest_amount
    }

    // double total_principal_amount = 42;

    pub fn clear_total_principal_amount(&mut self) {
        self.total_principal_amount = 0.;
    }

    // Param is passed by value, moved
    pub fn set_total_principal_amount(&mut self, v: f64) {
        self.total_principal_amount = v;
    }

    pub fn get_total_principal_amount(&self) -> f64 {
        self.total_principal_amount
    }

    // repeated .Cashflow cashflows = 43;

    pub fn clear_cashflows(&mut self) {
        self.cashflows.clear();
    }

    // Param is passed by value, moved
    pub fn set_cashflows(&mut self, v: ::protobuf::RepeatedField<Cashflow>) {
        self.cashflows = v;
    }

    // Mutable pointer to the field.
    pub fn mut_cashflows(&mut self) -> &mut ::protobuf::RepeatedField<Cashflow> {
        &mut self.cashflows
    }

    // Take field
    pub fn take_cashflows(&mut self) -> ::protobuf::RepeatedField<Cashflow> {
        ::std::mem::replace(&mut self.cashflows, ::protobuf::RepeatedField::new())
    }

    pub fn get_cashflows(&self) -> &[Cashflow] {
        &self.cashflows
    }
}

impl ::protobuf::Message for AccountWithCashflows {
    fn is_initialized(&self) -> bool {
        for v in &self.cashflows {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.account_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.currency)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.int_rate = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.outstanding_bal = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.gl = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.start_date = tmp;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.maturity_date = tmp;
                },
                8 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.customer_id)?;
                },
                9 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.customer_type)?;
                },
                10 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.lcy_amount = tmp;
                },
                11 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.reference)?;
                },
                12 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.npa_flag)?;
                },
                13 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.npa_type)?;
                },
                14 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.interest_type)?;
                },
                15 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.int_repayment_frequency = tmp;
                },
                16 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.last_repr_date = tmp;
                },
                17 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.next_repr_date = tmp;
                },
                18 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.cust_constitution_code = tmp;
                },
                19 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rate_flag)?;
                },
                20 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.customer_name)?;
                },
                21 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.product_code)?;
                },
                22 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.account_type)?;
                },
                23 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.branch)?;
                },
                24 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.rm)?;
                },
                25 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.group_code)?;
                },
                26 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.monthly_avg_bal)?;
                },
                27 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.aorl)?;
                },
                28 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.rl1 = tmp;
                },
                29 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.rl2 = tmp;
                },
                30 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.rl3 = tmp;
                },
                31 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.customer_rating)?;
                },
                32 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.p2)?;
                },
                33 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.waiver_flag)?;
                },
                34 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.accrued_int_amt)?;
                },
                35 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.string1)?;
                },
                36 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.string2)?;
                },
                37 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.string3)?;
                },
                38 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.number1 = tmp;
                },
                39 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.number2 = tmp;
                },
                40 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.number3 = tmp;
                },
                41 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.total_interest_amount = tmp;
                },
                42 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.total_principal_amount = tmp;
                },
                43 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.cashflows)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.account_id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.account_id);
        }
        if !self.currency.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.currency);
        }
        if self.int_rate != 0. {
            my_size += 9;
        }
        if self.outstanding_bal != 0. {
            my_size += 9;
        }
        if self.gl != 0 {
            my_size += ::protobuf::rt::value_size(5, self.gl, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.start_date != 0 {
            my_size += ::protobuf::rt::value_size(6, self.start_date, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.maturity_date != 0 {
            my_size += ::protobuf::rt::value_size(7, self.maturity_date, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.customer_id.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.customer_id);
        }
        if !self.customer_type.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.customer_type);
        }
        if self.lcy_amount != 0. {
            my_size += 9;
        }
        if !self.reference.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.reference);
        }
        if !self.npa_flag.is_empty() {
            my_size += ::protobuf::rt::string_size(12, &self.npa_flag);
        }
        if !self.npa_type.is_empty() {
            my_size += ::protobuf::rt::string_size(13, &self.npa_type);
        }
        if !self.interest_type.is_empty() {
            my_size += ::protobuf::rt::string_size(14, &self.interest_type);
        }
        if self.int_repayment_frequency != 0 {
            my_size += ::protobuf::rt::value_size(15, self.int_repayment_frequency, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.last_repr_date != 0 {
            my_size += ::protobuf::rt::value_size(16, self.last_repr_date, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.next_repr_date != 0 {
            my_size += ::protobuf::rt::value_size(17, self.next_repr_date, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.cust_constitution_code != 0 {
            my_size += ::protobuf::rt::value_size(18, self.cust_constitution_code, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.rate_flag.is_empty() {
            my_size += ::protobuf::rt::string_size(19, &self.rate_flag);
        }
        if !self.customer_name.is_empty() {
            my_size += ::protobuf::rt::string_size(20, &self.customer_name);
        }
        if !self.product_code.is_empty() {
            my_size += ::protobuf::rt::string_size(21, &self.product_code);
        }
        if !self.account_type.is_empty() {
            my_size += ::protobuf::rt::string_size(22, &self.account_type);
        }
        if !self.branch.is_empty() {
            my_size += ::protobuf::rt::string_size(23, &self.branch);
        }
        if !self.rm.is_empty() {
            my_size += ::protobuf::rt::string_size(24, &self.rm);
        }
        if !self.group_code.is_empty() {
            my_size += ::protobuf::rt::string_size(25, &self.group_code);
        }
        if !self.monthly_avg_bal.is_empty() {
            my_size += ::protobuf::rt::string_size(26, &self.monthly_avg_bal);
        }
        if !self.aorl.is_empty() {
            my_size += ::protobuf::rt::string_size(27, &self.aorl);
        }
        if self.rl1 != 0 {
            my_size += ::protobuf::rt::value_size(28, self.rl1, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.rl2 != 0 {
            my_size += ::protobuf::rt::value_size(29, self.rl2, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.rl3 != 0 {
            my_size += ::protobuf::rt::value_size(30, self.rl3, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.customer_rating.is_empty() {
            my_size += ::protobuf::rt::string_size(31, &self.customer_rating);
        }
        if !self.p2.is_empty() {
            my_size += ::protobuf::rt::string_size(32, &self.p2);
        }
        if !self.waiver_flag.is_empty() {
            my_size += ::protobuf::rt::string_size(33, &self.waiver_flag);
        }
        if !self.accrued_int_amt.is_empty() {
            my_size += ::protobuf::rt::string_size(34, &self.accrued_int_amt);
        }
        if !self.string1.is_empty() {
            my_size += ::protobuf::rt::string_size(35, &self.string1);
        }
        if !self.string2.is_empty() {
            my_size += ::protobuf::rt::string_size(36, &self.string2);
        }
        if !self.string3.is_empty() {
            my_size += ::protobuf::rt::string_size(37, &self.string3);
        }
        if self.number1 != 0 {
            my_size += ::protobuf::rt::value_size(38, self.number1, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.number2 != 0 {
            my_size += ::protobuf::rt::value_size(39, self.number2, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.number3 != 0 {
            my_size += ::protobuf::rt::value_size(40, self.number3, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_interest_amount != 0. {
            my_size += 10;
        }
        if self.total_principal_amount != 0. {
            my_size += 10;
        }
        for value in &self.cashflows {
            let len = value.compute_size();
            my_size += 2 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.account_id.is_empty() {
            os.write_string(1, &self.account_id)?;
        }
        if !self.currency.is_empty() {
            os.write_string(2, &self.currency)?;
        }
        if self.int_rate != 0. {
            os.write_double(3, self.int_rate)?;
        }
        if self.outstanding_bal != 0. {
            os.write_double(4, self.outstanding_bal)?;
        }
        if self.gl != 0 {
            os.write_int64(5, self.gl)?;
        }
        if self.start_date != 0 {
            os.write_int64(6, self.start_date)?;
        }
        if self.maturity_date != 0 {
            os.write_int64(7, self.maturity_date)?;
        }
        if !self.customer_id.is_empty() {
            os.write_string(8, &self.customer_id)?;
        }
        if !self.customer_type.is_empty() {
            os.write_string(9, &self.customer_type)?;
        }
        if self.lcy_amount != 0. {
            os.write_double(10, self.lcy_amount)?;
        }
        if !self.reference.is_empty() {
            os.write_string(11, &self.reference)?;
        }
        if !self.npa_flag.is_empty() {
            os.write_string(12, &self.npa_flag)?;
        }
        if !self.npa_type.is_empty() {
            os.write_string(13, &self.npa_type)?;
        }
        if !self.interest_type.is_empty() {
            os.write_string(14, &self.interest_type)?;
        }
        if self.int_repayment_frequency != 0 {
            os.write_int64(15, self.int_repayment_frequency)?;
        }
        if self.last_repr_date != 0 {
            os.write_int64(16, self.last_repr_date)?;
        }
        if self.next_repr_date != 0 {
            os.write_int64(17, self.next_repr_date)?;
        }
        if self.cust_constitution_code != 0 {
            os.write_int64(18, self.cust_constitution_code)?;
        }
        if !self.rate_flag.is_empty() {
            os.write_string(19, &self.rate_flag)?;
        }
        if !self.customer_name.is_empty() {
            os.write_string(20, &self.customer_name)?;
        }
        if !self.product_code.is_empty() {
            os.write_string(21, &self.product_code)?;
        }
        if !self.account_type.is_empty() {
            os.write_string(22, &self.account_type)?;
        }
        if !self.branch.is_empty() {
            os.write_string(23, &self.branch)?;
        }
        if !self.rm.is_empty() {
            os.write_string(24, &self.rm)?;
        }
        if !self.group_code.is_empty() {
            os.write_string(25, &self.group_code)?;
        }
        if !self.monthly_avg_bal.is_empty() {
            os.write_string(26, &self.monthly_avg_bal)?;
        }
        if !self.aorl.is_empty() {
            os.write_string(27, &self.aorl)?;
        }
        if self.rl1 != 0 {
            os.write_int32(28, self.rl1)?;
        }
        if self.rl2 != 0 {
            os.write_int32(29, self.rl2)?;
        }
        if self.rl3 != 0 {
            os.write_int32(30, self.rl3)?;
        }
        if !self.customer_rating.is_empty() {
            os.write_string(31, &self.customer_rating)?;
        }
        if !self.p2.is_empty() {
            os.write_string(32, &self.p2)?;
        }
        if !self.waiver_flag.is_empty() {
            os.write_string(33, &self.waiver_flag)?;
        }
        if !self.accrued_int_amt.is_empty() {
            os.write_string(34, &self.accrued_int_amt)?;
        }
        if !self.string1.is_empty() {
            os.write_string(35, &self.string1)?;
        }
        if !self.string2.is_empty() {
            os.write_string(36, &self.string2)?;
        }
        if !self.string3.is_empty() {
            os.write_string(37, &self.string3)?;
        }
        if self.number1 != 0 {
            os.write_int64(38, self.number1)?;
        }
        if self.number2 != 0 {
            os.write_int64(39, self.number2)?;
        }
        if self.number3 != 0 {
            os.write_int64(40, self.number3)?;
        }
        if self.total_interest_amount != 0. {
            os.write_double(41, self.total_interest_amount)?;
        }
        if self.total_principal_amount != 0. {
            os.write_double(42, self.total_principal_amount)?;
        }
        for v in &self.cashflows {
            os.write_tag(43, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AccountWithCashflows {
        AccountWithCashflows::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "account_id",
                    |m: &AccountWithCashflows| { &m.account_id },
                    |m: &mut AccountWithCashflows| { &mut m.account_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "currency",
                    |m: &AccountWithCashflows| { &m.currency },
                    |m: &mut AccountWithCashflows| { &mut m.currency },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "int_rate",
                    |m: &AccountWithCashflows| { &m.int_rate },
                    |m: &mut AccountWithCashflows| { &mut m.int_rate },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "outstanding_bal",
                    |m: &AccountWithCashflows| { &m.outstanding_bal },
                    |m: &mut AccountWithCashflows| { &mut m.outstanding_bal },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "gl",
                    |m: &AccountWithCashflows| { &m.gl },
                    |m: &mut AccountWithCashflows| { &mut m.gl },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "start_date",
                    |m: &AccountWithCashflows| { &m.start_date },
                    |m: &mut AccountWithCashflows| { &mut m.start_date },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "maturity_date",
                    |m: &AccountWithCashflows| { &m.maturity_date },
                    |m: &mut AccountWithCashflows| { &mut m.maturity_date },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "customer_id",
                    |m: &AccountWithCashflows| { &m.customer_id },
                    |m: &mut AccountWithCashflows| { &mut m.customer_id },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "customer_type",
                    |m: &AccountWithCashflows| { &m.customer_type },
                    |m: &mut AccountWithCashflows| { &mut m.customer_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "lcy_amount",
                    |m: &AccountWithCashflows| { &m.lcy_amount },
                    |m: &mut AccountWithCashflows| { &mut m.lcy_amount },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "reference",
                    |m: &AccountWithCashflows| { &m.reference },
                    |m: &mut AccountWithCashflows| { &mut m.reference },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "npa_flag",
                    |m: &AccountWithCashflows| { &m.npa_flag },
                    |m: &mut AccountWithCashflows| { &mut m.npa_flag },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "npa_type",
                    |m: &AccountWithCashflows| { &m.npa_type },
                    |m: &mut AccountWithCashflows| { &mut m.npa_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "interest_type",
                    |m: &AccountWithCashflows| { &m.interest_type },
                    |m: &mut AccountWithCashflows| { &mut m.interest_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "int_repayment_frequency",
                    |m: &AccountWithCashflows| { &m.int_repayment_frequency },
                    |m: &mut AccountWithCashflows| { &mut m.int_repayment_frequency },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "last_repr_date",
                    |m: &AccountWithCashflows| { &m.last_repr_date },
                    |m: &mut AccountWithCashflows| { &mut m.last_repr_date },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "next_repr_date",
                    |m: &AccountWithCashflows| { &m.next_repr_date },
                    |m: &mut AccountWithCashflows| { &mut m.next_repr_date },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "cust_constitution_code",
                    |m: &AccountWithCashflows| { &m.cust_constitution_code },
                    |m: &mut AccountWithCashflows| { &mut m.cust_constitution_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rate_flag",
                    |m: &AccountWithCashflows| { &m.rate_flag },
                    |m: &mut AccountWithCashflows| { &mut m.rate_flag },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "customer_name",
                    |m: &AccountWithCashflows| { &m.customer_name },
                    |m: &mut AccountWithCashflows| { &mut m.customer_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "product_code",
                    |m: &AccountWithCashflows| { &m.product_code },
                    |m: &mut AccountWithCashflows| { &mut m.product_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "account_type",
                    |m: &AccountWithCashflows| { &m.account_type },
                    |m: &mut AccountWithCashflows| { &mut m.account_type },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "branch",
                    |m: &AccountWithCashflows| { &m.branch },
                    |m: &mut AccountWithCashflows| { &mut m.branch },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "rm",
                    |m: &AccountWithCashflows| { &m.rm },
                    |m: &mut AccountWithCashflows| { &mut m.rm },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "group_code",
                    |m: &AccountWithCashflows| { &m.group_code },
                    |m: &mut AccountWithCashflows| { &mut m.group_code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "monthly_avg_bal",
                    |m: &AccountWithCashflows| { &m.monthly_avg_bal },
                    |m: &mut AccountWithCashflows| { &mut m.monthly_avg_bal },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "aorl",
                    |m: &AccountWithCashflows| { &m.aorl },
                    |m: &mut AccountWithCashflows| { &mut m.aorl },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "rl1",
                    |m: &AccountWithCashflows| { &m.rl1 },
                    |m: &mut AccountWithCashflows| { &mut m.rl1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "rl2",
                    |m: &AccountWithCashflows| { &m.rl2 },
                    |m: &mut AccountWithCashflows| { &mut m.rl2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                    "rl3",
                    |m: &AccountWithCashflows| { &m.rl3 },
                    |m: &mut AccountWithCashflows| { &mut m.rl3 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "customer_rating",
                    |m: &AccountWithCashflows| { &m.customer_rating },
                    |m: &mut AccountWithCashflows| { &mut m.customer_rating },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "p2",
                    |m: &AccountWithCashflows| { &m.p2 },
                    |m: &mut AccountWithCashflows| { &mut m.p2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "waiver_flag",
                    |m: &AccountWithCashflows| { &m.waiver_flag },
                    |m: &mut AccountWithCashflows| { &mut m.waiver_flag },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "accrued_int_amt",
                    |m: &AccountWithCashflows| { &m.accrued_int_amt },
                    |m: &mut AccountWithCashflows| { &mut m.accrued_int_amt },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "string1",
                    |m: &AccountWithCashflows| { &m.string1 },
                    |m: &mut AccountWithCashflows| { &mut m.string1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "string2",
                    |m: &AccountWithCashflows| { &m.string2 },
                    |m: &mut AccountWithCashflows| { &mut m.string2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "string3",
                    |m: &AccountWithCashflows| { &m.string3 },
                    |m: &mut AccountWithCashflows| { &mut m.string3 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "number1",
                    |m: &AccountWithCashflows| { &m.number1 },
                    |m: &mut AccountWithCashflows| { &mut m.number1 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "number2",
                    |m: &AccountWithCashflows| { &m.number2 },
                    |m: &mut AccountWithCashflows| { &mut m.number2 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                    "number3",
                    |m: &AccountWithCashflows| { &m.number3 },
                    |m: &mut AccountWithCashflows| { &mut m.number3 },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "total_interest_amount",
                    |m: &AccountWithCashflows| { &m.total_interest_amount },
                    |m: &mut AccountWithCashflows| { &mut m.total_interest_amount },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                    "total_principal_amount",
                    |m: &AccountWithCashflows| { &m.total_principal_amount },
                    |m: &mut AccountWithCashflows| { &mut m.total_principal_amount },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Cashflow>>(
                    "cashflows",
                    |m: &AccountWithCashflows| { &m.cashflows },
                    |m: &mut AccountWithCashflows| { &mut m.cashflows },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<AccountWithCashflows>(
                    "AccountWithCashflows",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AccountWithCashflows {
        static mut instance: ::protobuf::lazy::Lazy<AccountWithCashflows> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AccountWithCashflows,
        };
        unsafe {
            instance.get(AccountWithCashflows::new)
        }
    }
}

impl ::protobuf::Clear for AccountWithCashflows {
    fn clear(&mut self) {
        self.clear_account_id();
        self.clear_currency();
        self.clear_int_rate();
        self.clear_outstanding_bal();
        self.clear_gl();
        self.clear_start_date();
        self.clear_maturity_date();
        self.clear_customer_id();
        self.clear_customer_type();
        self.clear_lcy_amount();
        self.clear_reference();
        self.clear_npa_flag();
        self.clear_npa_type();
        self.clear_interest_type();
        self.clear_int_repayment_frequency();
        self.clear_last_repr_date();
        self.clear_next_repr_date();
        self.clear_cust_constitution_code();
        self.clear_rate_flag();
        self.clear_customer_name();
        self.clear_product_code();
        self.clear_account_type();
        self.clear_branch();
        self.clear_rm();
        self.clear_group_code();
        self.clear_monthly_avg_bal();
        self.clear_aorl();
        self.clear_rl1();
        self.clear_rl2();
        self.clear_rl3();
        self.clear_customer_rating();
        self.clear_p2();
        self.clear_waiver_flag();
        self.clear_accrued_int_amt();
        self.clear_string1();
        self.clear_string2();
        self.clear_string3();
        self.clear_number1();
        self.clear_number2();
        self.clear_number3();
        self.clear_total_interest_amount();
        self.clear_total_principal_amount();
        self.clear_cashflows();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AccountWithCashflows {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AccountWithCashflows {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x18proto/import_loans.proto\"R\n\x08Cashflow\x12\x17\n\x07int_amt\x18\
    \x01\x20\x01(\x01R\x06intAmt\x12\x19\n\x08prin_amt\x18\x02\x20\x01(\x01R\
    \x07prinAmt\x12\x12\n\x04date\x18\x03\x20\x01(\x03R\x04date\"\xf3\n\n\
    \x14AccountWithCashflows\x12\x1d\n\naccount_id\x18\x01\x20\x01(\tR\tacco\
    untId\x12\x1a\n\x08currency\x18\x02\x20\x01(\tR\x08currency\x12\x19\n\
    \x08int_rate\x18\x03\x20\x01(\x01R\x07intRate\x12'\n\x0foutstanding_bal\
    \x18\x04\x20\x01(\x01R\x0eoutstandingBal\x12\x0e\n\x02gl\x18\x05\x20\x01\
    (\x03R\x02gl\x12\x1d\n\nstart_date\x18\x06\x20\x01(\x03R\tstartDate\x12#\
    \n\rmaturity_date\x18\x07\x20\x01(\x03R\x0cmaturityDate\x12\x1f\n\x0bcus\
    tomer_id\x18\x08\x20\x01(\tR\ncustomerId\x12#\n\rcustomer_type\x18\t\x20\
    \x01(\tR\x0ccustomerType\x12\x1d\n\nlcy_amount\x18\n\x20\x01(\x01R\tlcyA\
    mount\x12\x1c\n\treference\x18\x0b\x20\x01(\tR\treference\x12\x19\n\x08n\
    pa_flag\x18\x0c\x20\x01(\tR\x07npaFlag\x12\x19\n\x08npa_type\x18\r\x20\
    \x01(\tR\x07npaType\x12#\n\rinterest_type\x18\x0e\x20\x01(\tR\x0cinteres\
    tType\x126\n\x17int_repayment_frequency\x18\x0f\x20\x01(\x03R\x15intRepa\
    ymentFrequency\x12$\n\x0elast_repr_date\x18\x10\x20\x01(\x03R\x0clastRep\
    rDate\x12$\n\x0enext_repr_date\x18\x11\x20\x01(\x03R\x0cnextReprDate\x12\
    4\n\x16cust_constitution_code\x18\x12\x20\x01(\x03R\x14custConstitutionC\
    ode\x12\x1b\n\trate_flag\x18\x13\x20\x01(\tR\x08rateFlag\x12#\n\rcustome\
    r_name\x18\x14\x20\x01(\tR\x0ccustomerName\x12!\n\x0cproduct_code\x18\
    \x15\x20\x01(\tR\x0bproductCode\x12!\n\x0caccount_type\x18\x16\x20\x01(\
    \tR\x0baccountType\x12\x16\n\x06branch\x18\x17\x20\x01(\tR\x06branch\x12\
    \x0e\n\x02rm\x18\x18\x20\x01(\tR\x02rm\x12\x1d\n\ngroup_code\x18\x19\x20\
    \x01(\tR\tgroupCode\x12&\n\x0fmonthly_avg_bal\x18\x1a\x20\x01(\tR\rmonth\
    lyAvgBal\x12\x12\n\x04aorl\x18\x1b\x20\x01(\tR\x04aorl\x12\x10\n\x03rl1\
    \x18\x1c\x20\x01(\x05R\x03rl1\x12\x10\n\x03rl2\x18\x1d\x20\x01(\x05R\x03\
    rl2\x12\x10\n\x03rl3\x18\x1e\x20\x01(\x05R\x03rl3\x12'\n\x0fcustomer_rat\
    ing\x18\x1f\x20\x01(\tR\x0ecustomerRating\x12\x0e\n\x02p2\x18\x20\x20\
    \x01(\tR\x02p2\x12\x1f\n\x0bwaiver_flag\x18!\x20\x01(\tR\nwaiverFlag\x12\
    &\n\x0faccrued_int_amt\x18\"\x20\x01(\tR\raccruedIntAmt\x12\x18\n\x07str\
    ing1\x18#\x20\x01(\tR\x07string1\x12\x18\n\x07string2\x18$\x20\x01(\tR\
    \x07string2\x12\x18\n\x07string3\x18%\x20\x01(\tR\x07string3\x12\x18\n\
    \x07number1\x18&\x20\x01(\x03R\x07number1\x12\x18\n\x07number2\x18'\x20\
    \x01(\x03R\x07number2\x12\x18\n\x07number3\x18(\x20\x01(\x03R\x07number3\
    \x122\n\x15total_interest_amount\x18)\x20\x01(\x01R\x13totalInterestAmou\
    nt\x124\n\x16total_principal_amount\x18*\x20\x01(\x01R\x14totalPrincipal\
    Amount\x12'\n\tcashflows\x18+\x20\x03(\x0b2\t.CashflowR\tcashflowsb\x06p\
    roto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
