[package]
name = "cf_bonds_fra"
version = "1.0.2587"
authors = ["JananiPrakasam <janani.p@surya-soft.com>"]

[dependencies]
clap = "3.0.14"
chrono = "0.4.19"
rbdate = { path = "../../../libraries/RBDate" }
sdb_io = { path = "../../../libraries/sdb_io"}
health_report = { path = "../../../libraries/health_report" }
protobuf = { version = "2.27.1", features = ["with-bytes"] }
serde = "1.0.136"
serde_json = "1.0.79"
serde_derive = "1.0.136"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.8.1"
slog-async = "2.7.0"
