#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InputAccount {
    pub acc_no: String,
    pub acnts_internal_acnum: String,
    pub acnts_brn_code: String,
    pub acnts_client_num: String,
    pub ucic: String,
    pub acnts_curr_code: String,
    pub acnts_prod_code: String,
    pub gl_cd: String,
    pub acc_open_dt: String,
    pub bal: String,
    pub balccy: String,
    pub int_rate: String,
    pub int_type: String,
    pub int_bench: String,
    pub int_spread: String,
    pub last_reset_dt: String,
    pub next_reset_dt: String,
    pub reset_no_of_months: String,
    pub int_accrued_amt: String,
    pub constitn: String,
    pub lm_exp: String,
    pub lim: String,
    pub lm_ccy: String,
    pub ext_rating_agency: String,
    pub ext_rating: String,
    pub int_rating: String,
    pub asset_cd: String,
    pub provision_amt: String,
    pub prov_dt: String,
    pub ason: String,
}

impl InputAccount {
    pub fn print(&self) -> String {
        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|{}|",
            self.acc_no,
            self.acnts_internal_acnum,
            self.acnts_brn_code,
            self.acnts_client_num,
            self.ucic,
            self.acnts_curr_code,
            self.acnts_prod_code,
            self.gl_cd,
            self.acc_open_dt,
            self.bal,
            self.balccy,
            self.int_rate,
            self.int_type,
            self.int_bench,
            self.int_spread,
            self.last_reset_dt,
            self.next_reset_dt,
            self.reset_no_of_months,
            self.int_accrued_amt,
            self.constitn,
            self.lm_exp,
            self.lim,
            self.lm_ccy,
            self.ext_rating_agency,
            self.ext_rating,
            self.int_rating,
            self.asset_cd,
            self.provision_amt,
            self.prov_dt,
        )
    }
}
