[package]
name = "undrawn_moc"
version = "0.1.4513"
author= ["SachinMulgir <sachin.m@surya-soft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
calamine = "0.15.3"
chrono = "0.4"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }

# This rbdate library path is relative so this might be needed to change as per config
health_report = { path = "/home/sachinm/Desktop/Surya/SuperDB-Batch/hdfc/libraries/health_report" }
rbdate = { path = "/home/sachinm/Desktop/Surya/SuperDB-Batch/hdfc//libraries/RBDate" }
sdb_io = { path = "/home/sachinm/Desktop/Surya/SuperDB-Batch/hdfc/libraries/sdb_io" }
serde_json = "1.0.81"
serde_derive = "1.0"
serde = "1.0"
sdb_dyn_proto_rdr = { path = "/home/sachinm/Desktop/Surya/SuperDB-Batch/hdfc/libraries/sdb_dyn_proto_rdr" }

