[package]
name = "ftp-stamper-dep"
version = "1.7.4192"
authors = ["Srinivas Reddy srinivas.r@surya-soft.com"]

[dependencies]
clap="2.31.2"
sdb_dyn_proto_rdr = { path = "../../../libraries/sdb_dyn_proto_rdr" }
sdb_agg_rules = { path = "../../../../surya/libraries/sdb_agg_rules" }
sdb_agg_rules_adj = { path = "../../../libraries/sdb_agg_rules_adj" }
sdb_io ={path = "../../../libraries/sdb_io" }
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
chrono = "0.4"
rbconcurrency = { path = "../../../libraries/RBConcurrency" }
rbdate = { path = "../../../libraries/RBDate" }
protobuf = { version = "2.17.0", features = ["with-bytes"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
libmath = "0.2.1"
