[package]
name = "cf_lcr"
version = "1.0.4358"
authors = ["VishwasBhat99 <vishwas.b@surya-soft.com>"]

[dependencies]
calamine = "0.15.3"
clap = "2.32.0"
chrono = "0.4"
health_report = {path = "../../../../hdfc/libraries/health_report"}
protobuf = { version = "2.16.2", features = ["with-bytes"] }
rbdate = { path = "../../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../../hdfc/libraries/sdb_io"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
slog = { version = "2.2.3", features = ["max_level_trace", "release_max_level_trace"] }
slog-term = "2.4.0"
slog-async = "2.3.0"
