OPTIONS (SKIP=1)
LOAD DATA
INFILE '/data3/Release/Basel_Custid_level_28_Oct_2019.txt' "STR '\r\n'"
TRUNCATE
INTO TABLE BIU_S2 FIELDS TERMINATED BY '|'
 TRAILING NULLCOLS 
(
COD_CUST,
SAL_TXN,
T4_FLAG,
TRANSX_FLAG_2_OTHERS,
CUSTOMER_TYPE,
NATURE_OF_BUS,
TXT_BUS_DESC,
)
