[package]
name = "ftp_old_new_conv"
version = "1.2.0"
authors = ["Tarun Jaiswal <tarun.j@surya-soft.com>"]
edition = "2018"

[dependencies]
rbdate = { path = "../../../hdfc/libraries/RBDate" }
sdb_io = { path = "../../../hdfc/libraries/sdb_io" }
clap = "2.33.0"
chrono = "0.4.10"
health_report = { path = "../../../hdfc/libraries/health_report" }
csv = "1.1.1"
serde = "1.0.104"
serde_derive = "1.0.104"
