use chrono::NaiveDate;

pub struct OutputData {
    pub ubs_account_number: String,
    pub cust_id: i64,
    pub deal_name: String,
    pub principal_amount: f64,
    pub deal_start_date: String,
    pub cf_end_date: String,
    pub accrued_interest: f64,
    pub compounding_frequency: String,
    pub deal_value: i64,
    pub gl: i64,
    pub system: String,
    pub curr_nominal_int_rate: i64,
    pub ratings: String,
    pub rating_aggency: String,
    pub asset_class: String,
    pub division: String,
    pub typ: String,
    pub originator: String,
    pub contract_yield: f64,
    pub current_annual_yield: f64,
    pub reset_frequency: String,
    pub interest_rate_type: String,
    pub expected_rate_reset_date: String,
    pub date1: String,
    pub intrest_portion: f64,
    pub principal_payment: f64,
    pub yld: f64,
    pub mis_code_1: i64,
    pub mis_code_2: i64,
}
