#[derive(Debug, Clone)]
pub struct AccFieldNames {
    pub account_number: String,
    pub accrued_interest: String,
    pub deposit_type: String,
    pub current_book_balance: String,
    pub maturity_date: String,
    pub rat_acct_int: String,
    pub rat_acct_int_var: String,
    pub next_compound_date: String,
    pub next_payment_date: String,
    pub account_start_date: String,
    pub currency_code: String,
    pub customer_id: String,
    pub original_balance: String,
    pub origination_date: String,
    pub previous_roll_over_date: String,
    pub description: String,
    pub gl_liab: String,
    pub client_name: String,
    pub t_name: String,
    pub as_of_date: String,
    pub bank_number: String,
    pub branch: String,
    pub cost_centre_ftp: String,
    pub gl_account_number: String,
    pub interest_rate: String,
    pub rate_flag: String,
    pub interest_payment_frequency: String,
    pub institution: String,
    pub concat: String,
    pub compounding_frequency: String,
    pub cashflows: String,
}

impl AccFieldNames {
    pub fn get_input_fields_names() -> AccFieldNames {
        AccFieldNames {
            account_number: "account_number".to_string(),
            accrued_interest: "accrued_interest".to_string(),
            deposit_type: "deposit_type".to_string(),
            current_book_balance: "current_book_balance".to_string(),
            maturity_date: "maturity_date".to_string(),
            rat_acct_int: "rat_acct_int".to_string(),
            rat_acct_int_var: "rat_acct_int_var".to_string(),
            next_compound_date: "next_compound_date".to_string(),
            next_payment_date: "next_payment_date".to_string(),
            account_start_date: "account_start_date".to_string(),
            currency_code: "currency_code".to_string(),
            customer_id: "customer_id".to_string(),
            original_balance: "original_balance".to_string(),
            origination_date: "origination_date".to_string(),
            previous_roll_over_date: "previous_roll_over_date".to_string(),
            description: "description".to_string(),
            gl_liab: "gl_liab".to_string(),
            client_name: "client_name".to_string(),
            t_name: "t_name".to_string(),
            as_of_date: "as_of_date".to_string(),
            bank_number: "bank_number".to_string(),
            branch: "branch".to_string(),
            cost_centre_ftp: "cost_centre_ftp".to_string(),
            gl_account_number: "gl_account_number".to_string(),
            interest_rate: "interest_rate".to_string(),
            rate_flag: "rate_flag".to_string(),
            interest_payment_frequency: "interest_payment_frequency".to_string(),
            institution: "institution".to_string(),
            concat: "concat".to_string(),
            compounding_frequency: "compounding_frequency".to_string(),
            cashflows: "cashflows".to_string(),
        }
    }
}
